### ISSUE TITLE
How to run eventgen (new version) as command line with Splunk installation option?

### ISSUE THREAD

**Issue by getkub** [splunk/eventgen#113]
since many of our internal systems cannot support pip and automated downloads from internet, the only option available to us is to use the SA-Eventgen app.

We are looking for option like:
`
$SPLUNK_HOME/bin/splunk bin python $SPLUNK_HOME/etc/apps/SA-Eventgen/bin/modinput_eventgen.py tests/sample_eventgen_conf/replay/eventgen.conf.replay
`
Is it possible with new version? (the old version, we were able to do similar and provided great useability on respective conf file)

**Comment by lephino** [comment]
before I say "this is possible" I need to test it, BUT if you wanna look ahead, we ship the full eventgen library under the sa-eventgen/lib directory.  IN theory, you could use it just like the cmd type doing splunk bin python <path>.  Now my question is, why use it over mod inputs?  You can add as many modinputs as you need which are effectively doing the exact same thing.

**Comment by getkub** [comment]
thanks for your info. There are plenty of circumstances, I can think we can't use mod inputs
- in scenario's we can't touch splunk application, but has to load simulation data externally.
- Automated scripts which can hand-over to other team to generate data on a click without giving them access to Splunk
- Create outputMode as file without need of Splunk

(these scenario's all can be done via pip mode of install, but we can't access outside network within the server)

**Comment by arctan5x** [comment]
Yes. Confirming that SA-Eventgen -> lib -> splunk_eventgen is a full eventgen python package. You can reference __main__.py inside of splunk_eventgen to run Eventgen as a standalone Python module.

Closing this issue. Feel free to reopen if you see fit.
