### ISSUE TITLE
"end" argument not working correctly with replay mode

### ISSUE THREAD

**Issue by jmeixensperger** [splunk/eventgen#130]
When I use replay mode and do NOT specify an "end" value, eventgen only generates 1 iteration of the sample and exits. Other time/count sensitive arguments like earliest, latest, count, and iteration seem to be working fine, but I cannot get it to produce a indefinite stream of events. Here's my conf and sample files (had to make them .txt files):

[eventgen.conf.txt](https://github.com/splunk/eventgen/files/2895540/eventgen.conf.txt)
[sample.txt](https://github.com/splunk/eventgen/files/2895541/sample.txt)

**Comment by jmeixensperger** [comment]
So it looks like this is the expected/designed behavior for replay mode (end is 1 by default). @arctan5x or @lephino , shouldn't the generation continue indefinitely, despite the mode? If not, this is something we should definitely add to the spec file.

**Comment by lephino** [comment]
Is end actually set to 1?  I'm fine if that's how it work, but I should be able to set end=0 or end=-1 to tell it to repeat forever.

**Comment by jmeixensperger** [comment]
Yes, it's only the case for replay mode though. You can still explicitly set it, but it should probably be consistent between modes.

**Comment by lephino** [comment]
not sure I know which is the more "common".  If I dump an index (with 1000000 events) or something, chances are, I just want it to repeat once?  I'm fine if you change the default back to 0 / -1, just make sure we call it out in the docs.
