### ISSUE TITLE
TypeError: sequence index must be integer, not 'str'

### ISSUE THREAD

**Issue by beyonddc** [splunk/eventgen#132]
This is my home lab, and I am trying to learn Splunk.  I am currently running Splunk version 7.2.0.  The Splunk instance is deployed as a Docker container.  The container image is obtained from the official Splunk's dockerhub repository.

`splunk@f90961e255bf:~/.local/lib/python2.7/site-packages/splunk_eventgen$ splunk_eventgen --version
Eventgen 6.3.3`

Following the instruction from https://splunk.github.io/eventgen/SETUP.html#pypi-installation, I am trying to exercise the eventgen the first time using `eventgen.conf.tutorial1`

The only changes I made in the eventgen.conf.tutorial1 is to change the outputMode to splunkstream and set the splunk password (see below).
`
[sample.tutorial1]
mode = replay
sampletype = csv
timeMultiple = 2
#backfill = -15m
#backfillSearch = index=main sourcetype=splunkd

#outputMode = stdout
outputMode = splunkstream
splunkHost = localhost
splunkUser = admin
splunkPass = password123
`

When I try to run it by executing `splunk@f90961e255bf:~/.local/lib/python2.7/site-packages/splunk_eventgen$ splunk_eventgen -v generate ./README/eventgen.conf.tutorial1`, I got the following error.
`
plunk@f90961e255bf:~/.local/lib/python2.7/site-packages/splunk_eventgen$ splunk_eventgen -v generate ./README/eventgen.conf.tutorial1
2019-03-01 05:59:42 eventgen        INFO     MainProcess Logging Setup Complete.
2019-03-01 05:59:42 eventgen        INFO     MainProcess Retrieving eventgen configurations with ConfigParser()
2019-03-01 05:59:42 eventgen        INFO     MainProcess Key 'verbose' in stanza 'global' may not be a valid setting
2019-03-01 05:59:42 eventgen        INFO     MainProcess Key 'splunkHost' in stanza 'sample.tutorial1' may not be a valid setting
2019-03-01 05:59:42 eventgen        INFO     MainProcess Key 'splunkUser' in stanza 'sample.tutorial1' may not be a valid setting
2019-03-01 05:59:42 eventgen        INFO     MainProcess Key 'splunkPass' in stanza 'sample.tutorial1' may not be a valid setting
2019-03-01 05:59:43 eventgen        INFO     MainProcess Creating timer object for sample 'sample.tutorial1' in app 'splunk_eventgen'
2019-03-01 05:59:43 eventgen        INFO     MainProcess Start '1' generatorWorkers for sample 'sample.tutorial1'
2019-03-01 05:59:43 eventgen        INFO     MainProcess All timers started, joining queue until it's empty.
2019-03-01 05:59:43 eventgen        INFO     MainProcess Start '1' generatorWorkers for sample 'sample.tutorial1'
2019-03-01 05:59:43 eventgen        INFO     MainProcess Worker# 0: Put 0.0 MB of events in queue for sample 'sample.tutorial1' with et '2019-03-01 05:59:43.109299' and lt '2019-03-01 05:59:43.109363'
2019-03-01 05:59:43 eventgen        ERROR    MainProcess sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/eventgen_core.py", line 352, in _generator_do_work
    item.run(output_counter=output_counter)
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/generatorplugin.py", line 213, in run
    self.gen(count=self.count, earliest=self.start_time, latest=self.end_time, samplename=self._sample.name)
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/plugins/generator/replay.py", line 128, in gen
    self.set_time_and_send(rpevent, self.backfill_time, earliest, latest)
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/plugins/generator/replay.py", line 57, in set_time_and_send
    self._out.bulksend([rpevent])
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/eventgenoutput.py", line 81, in bulksend
    self.flush()
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/eventgenoutput.py", line 130, in flush
    outputer.run()
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/outputplugin.py", line 51, in run
    self.flush(q=self.events)
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/lib/plugins/output/splunkstream.py", line 64, in flush
    queues[row['source']+'_'+row['sourcetype']] = deque([])
TypeError: sequence index must be integer, not 'str'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/splunk/.local/lib/python2.7/site-packages/splunk_eventgen/eventgen_core.py", line 361, in _generator_do_work
    raise e
TypeError: sequence index must be integer, not 'str'
`

It seems to run fine once I set the outputMode back to stdout.

Please shed some light on what I did wrong.  Thanks!

**Comment by arctan5x** [comment]
@jmeixensperger and I spoked and we identified this as a bug. We will fix it. Thanks for creating the issue.

**Comment by beyonddc** [comment]
Is there a workaround on this?  Such as switching to an older version of eventgen or switching to an older version of Splunk?

**Comment by arctan5x** [comment]
I would assume that older version of Eventgen would still not work with this. Changing to an older version of Splunk will have no effect on this. 

A wordaround would be changing your outputmode to something like tcp or httpevent. Those output methods still allow you to ingest data into your Splunk instance. Is there a particular reason why you need to Splunk stream?

**Comment by beyonddc** [comment]
No particular reason, I am trying to learn how to use eventgen to inject data into Splunk.

The output mode set in `eventgen.conf.tutorial1` by default is stdout, and subsequent lines of the following were commented out so my first assumption is if I only need to uncomment those lines and it would automatically inject data into Splunk.
```
#outputMode = splunkstream
#splunkHost = localhost
#splunkUser = admin
#splunkPass = changeme
```

I am learning Splunk, and the way how I get data into Splunk is by installing agent on the monitoring machines.  When you suggested to set outputMode to TCP or HTTPEvent, do you also imply configuring Splunk to listening to a specific TCP port or HTTP events as well?

Thanks!

**Comment by arctan5x** [comment]
I see.

Yes. It would be configuring settings -> data input to add either HTTP Event endpoint or TCP endpoint. I would suggest using HTTPEvent, since it is a reliable recommended way of data ingestion for Splunk. Give it a try and let me know how that goes. We are always here to help you debug it.

**Comment by jmeixensperger** [comment]
#133

**Comment by beyonddc** [comment]
Seems like it does the trick now after updating the outputMode to httpevent with proper httpevent settings when running it in standalone mode by executing 'splunk_eventgen generate ./Playground/Splunk/sample.tutorial1'.

```
outputMode = httpevent
httpeventServers = {"servers":[{ "protocol":"http", "address":"127.0.0.1", "port":"8888", "key":"8dcf0623-279f-4afe-9
httpeventOutputMode = mirror
```

I stopped the splunk_eventgen, installed SA-Eventgen app on Splunk, enabled modinput_eventgen and then copied the sample.tutorial1 directory to /opt/splunk/etc/apps.  After that, I restarted the Splunk instance.  I do not see any events generated.  Can you please let me know what I did wrong?

**Comment by jmeixensperger** [comment]
When using the app, Eventgen searches other Splunk apps to find any occurrences of eventgen.conf. There's some relevant information at the top of the tutorial page in our docs. You will have to install a TA and place your conf and sample files inside it before starting Eventgen.

**Comment by arctan5x** [comment]
Oh did not see that you are trying to use it as an app. 

Basically @jmeixensperger's response + i don't think you need an outputmode specified because Eventgen app will set it for you.

**Comment by beyonddc** [comment]
Thank you Jack and Tony for your explanation and tips.

Before I submit this issue, I originally trying to use the eventgen as a Splunk app but I was not able to get any events generated and the log files were not informative so I switched over to run the eventgen as a standalone Python application.

Anyhow, perhaps I misread the tutorial, my understanding is if you want to use the eventgen as a Splunk app, all you have to do is to create a directory structure like the following in `/opt/splunk/etc/apps`.
```
/opt/splunk/etc/apps
/opt/splunk/etc/apps/sample.tutorial1
/opt/splunk/etc/apps/sample.tutorial1/default
/opt/splunk/etc/apps/sample.tutorial1/default/eventgen.conf
/opt/splunk/etc/apps/sample.tutorial1/samples/sample.tutorial1
```

Upon restarting the Splunk instance, if eventgen is already installed as a Splunk app, it will automatically pickup the eventgen.conf that I placed in `/opt/splunk/etc/apps/sample.tutorial1/default` and start generating events using the `/opt/splunk/etc/apps/sample.tutorial1/samples/sample.tutorial1`

Is this not the case?

**Comment by arctan5x** [comment]
That is still the case :) This works because Eventgen App automatically triggers its embedded mode and starts looking for the conf files inside of /opt/splunk/etc/apps. When you do that, no need to supply the outputmode because Eventgen App will handle it.

**Comment by beyonddc** [comment]
Correct and that is where I am having issue with.

I created a directory structure like the following in `/opt/splunk/etc/apps`.
```
/opt/splunk/etc/apps
/opt/splunk/etc/apps/sample.tutorial1
/opt/splunk/etc/apps/sample.tutorial1/default
/opt/splunk/etc/apps/sample.tutorial1/default/eventgen.conf
/opt/splunk/etc/apps/sample.tutorial1/samples/sample.tutorial1
```

I updated eventgen.conf and didn't supply the outputMode.
```
[sample.tutorial1]
mode = replay
sampletype = csv
timeMultiple = 2
#backfill = -15m
#backfillSearch = index=main sourcetype=splunkd

#outputMode = stdout
#outputMode = splunkstream
#splunkHost = localhost
#splunkUser = admin
#splunkPass = secret

#outputMode = httpevent
#httpeventServers = {"servers":[{ "protocol":"http", "address":"127.0.0.1", "port":"8888", "key":"9e77bdb9-cff4-42be-bfc0-8e2902c5089c"}]}
#httpeventOutputMode = mirror

#outputMode = file
#fileName = /tmp/internal.log

token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3,6}
token.0.replacementType = timestamp
token.0.replacement = %Y-%m-%d %H:%M:%S,%f

token.1.token = \d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}.\d{3,6}
token.1.replacementType = timestamp
token.1.replacement = %m-%d-%Y %H:%M:%S.%f

token.2.token = \d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2}.\d{3,6}
token.2.replacementType = timestamp
token.2.replacement = %d/%b/%Y:%H:%M:%S.%f

token.3.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
token.3.replacementType = timestamp
token.3.replacement = %Y-%m-%d %H:%M:%S

token.4.token = \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}
token.4.replacementType = timestamp
token.4.replacement = %Y-%m-%dT%H:%M:%S
```

SA-Eventgen is already installed as Splunk App but when I restart the Splunk instance, no new events were being generated.  I am not sure what I did wrong.

**Comment by arctan5x** [comment]
did you set your app "sample.tutorial1" setting to global? Eventgen App can't access it if it isn't global setting. You can change this in "manage apps". Then underneath the "sharing" column, please set that to Global.

**Comment by beyonddc** [comment]
That was it!  Thanks Tony

I don't think that criteria was mentioned in the tutorial document.  Perhaps it should be updated?

**Comment by arctan5x** [comment]
Thanks for the feedback. Will update it. Closing the issue now.
