### ISSUE TITLE
Unable to get timeMultiple to work in replay mode

### ISSUE THREAD

**Issue by beyonddc** [splunk/eventgen#139]
I doubt this is a bug but I couldn't get the timeMultiple to work in replay mode.

It seems like every time eventgen executes, it will replay all of these syslog messages at once.  I see about 1000 events generated in Splunk after the eventgen executed.

Can anyone see anything wrong in my eventgen.conf?

```
[foo-rhel7-1.beyonddc.net_messages.csv]
mode = replay
sampletype = csv

# Only valid in mode = replay
# Will slow down the replay of events by <float> factor.  For example, allows a 10 minute sample
# to play out over 20 minutes with a timeMultiple of 2, or 60 minutes with a timeMultiple of 6.
# By the converse, make timeMultiple 0.5 will make the events run twice as fast. 
timeMultiple = 2
timeField = time
backfill = -15m
#backfillSearch = index=main sourcetype=splunkd

outputMode = httpevent
httpeventServers = {"servers":[{ "protocol":"http", "address":"127.0.0.1", "port":"8888", "key":"cfc4d103-bea4-4881-952a-99ce8746310c"}]}

# Replace timestamp Feb  4 07:52:53
token.0.token = \w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}
token.0.replacementType = timestamp
token.0.replacement = %b %d %H:%M:%S

token.1.token = (localhost)
token.1.replacementType = static
token.1.replacement = foo-rhel7-1.beyonddc.net
```

Snippet of my csv file
```
time,index,host,source,sourcetype,"_raw"
"Mar  3 03:39:02","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 03:39:02 localhost rsyslogd: [origin software="rsyslogd" swVersion="8.24.0" x-pid="1303" x-info="http://www.rsyslog.com"] rsyslogd was HUPed"
"Mar  3 04:13:22","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 04:13:22 localhost rsyslogd: imjournal: journal reloaded... [v8.24.0 try http://www.rsyslog.com/e/0 ]"
"Mar  3 15:42:07","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 15:42:07 localhost rsyslogd: imjournal: journal reloaded... [v8.24.0 try http://www.rsyslog.com/e/0 ]"
"Mar  3 15:42:07","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 15:42:07 localhost rsyslogd: imjournal: journal reloaded... [v8.24.0 try http://www.rsyslog.com/e/0 ]"
"Mar  3 22:15:09","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 22:15:09 localhost dockerd-current: time="2019-03-03T22:15:09.316981911-05:00" level=info msg="Container 51c5c0a32c88ed4fe4b33ebfceea7731e5be3853dc8d625e16b781f2a955eb11 failed to exit within 10 seconds of signal 15 - using the force""
"Mar  3 22:15:09","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 22:15:09 localhost dockerd-current: time="2019-03-03T22:15:09.571355247-05:00" level=error msg="containerd: deleting container" error="exit status 1: \"container 51c5c0a32c88ed4fe4b33ebfceea7731e5be3853dc8d625e16b781f2a955eb11 does not exist\\none or more of the container deletions failed\\n\"""
"Mar  3 22:15:09","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 22:15:09 localhost kernel: br-7e5eeb217214: port 1(veth250986b) entered disabled state"
"Mar  3 22:15:09","main","foo-rhel7-1.beyonddc.net","/var/log/messages",syslog,"Mar  3 22:15:09 localhost NetworkManager[962]: <info>  [1551669309.7185] manager: (veth850b1e1): new Veth device (/org/freedesktop/NetworkManager/Devices/55)"
```

[eventgen.conf.txt](https://github.com/splunk/eventgen/files/2932450/eventgen.conf.txt)
[foo-rhel7-1.beyonddc.net_messages.csv.txt](https://github.com/splunk/eventgen/files/2932453/foo-rhel7-1.beyonddc.net_messages.csv.txt)

**Comment by jmeixensperger** [comment]
There is definitely a bug with timeMultiple, as I'm not seeing it work in various scenarios for me either. There may also be something wrong with backfill that is causing those 1000 events to be generated, but I will look into it further.

**Comment by jmeixensperger** [comment]
The backfill timestamps aren't getting updated in replay mode, so the events all use the starting time of the backfill.

**Comment by beyonddc** [comment]
Umm.... so if I comment out the backfill for now then the timeMultiple would work?

**Comment by jmeixensperger** [comment]
No, sorry if that wasn't clear. timeMultiple is not currently working and we need to fix it.

I was wrong about the backfill though. @lephino pointed out that you should be using the "replaytimestamp" replacement type for your token 0.

**Comment by beyonddc** [comment]
Hi Jack,

I am trying to gain more understanding between the difference between timestamp and replaytimestamp.

Can 'replacementType=timestamp' be used during replay mode?  If so what are the fields used to calculate the interval on when one syslog message should be sent?

When 'replacementType=replaytimestamp' is used, is the calculation between message sent interval uses the the time difference between the current and next syslog event?  If that is the case then I probably do not need to specify the 'timeMultiple' and the 'timeField'.  Correct?

Thanks

==============================
* For timestamp, the token will be replaced with the strptime specified in the replacement setting

* For replaytimestamp, the token will be replaced with the strptime specified in the replacement setting but the time will not be based on earliest and latest, but will instead be replaced by looking at the offset of the timestamp in the current event versus the first event, and then adding that time difference to the timestamp when we started processing the sample.  This allows for replaying events with a new timestamp but to look much like the original transaction.  Assumes replacement value is the same strptime format as the original token we're replacing, otherwise it will fail.  First timestamp will be the value of earliest.  NOT TO BE CONFUSED WITH REPLAY MODE.  Replay mode replays a whole file with timing to look like the original file.  This will allow a single transaction to be replayed with some randomness.

**Comment by beyonddc** [comment]
I am doing more testing and just realized couple of things when observing the output on console when I set the 'outputMode=stdout'.

The syslog that I am replaying has 3 days worth of syslog messages.  When timestamp replacementType is set to 'replaytimestamp', the event generator will start from the current time and start generating all the events at once and when it finishes, the last timestamp shown in stdout is on March 10.

If I understand this correctly, I should be able to use the 'backfill' field and set it to -24h so the first generated event would starts from 2 days ago, is that correct?  However when I run it, nothing were display on the stdout.  I am assuming no events were generated.

Here's my current eventgen.conf
```
[foo-rhel7-1.beyonddc.net_messages.csv]
mode = replay
sampletype = csv

# Only valid in mode = replay
# Will slow down the replay of events by <float> factor.  For example, allows a 10 minute sample
# to play out over 20 minutes with a timeMultiple of 2, or 60 minutes with a timeMultiple of 6.
# By the converse, make timeMultiple 0.5 will make the events run twice as fast. 
#timeMultiple = 2
timeField = time
backfill = -24h
#backfillSearch = index=main sourcetype=splunkd

#outputMode = httpevent
outputMode = stdout
httpeventServers = {"servers":[{ "protocol":"http", "address":"127.0.0.1", "port":"8888", "key":"cfc4d103-bea4-4881-952a-99ce8746310c"}]}

# Replace timestamp Feb  4 07:52:53
token.0.token = \w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}
token.0.replacementType = replaytimestamp
token.0.replacement = %b %d %H:%M:%S

token.1.token = (mail)
token.1.replacementType = static
token.1.replacement = foo-rhel7-1.beyonddc.net
```

**Comment by beyonddc** [comment]
I think I am all set.  After playing with the eventgen with the outputmode set to stdout, I was able observe behavior of different parameters.

Here's my observation for getting dummy data into Splunk instance for testing and learning.

I think the replay mode is useful to populate events into Splunk instance.  It is important to set the 'earliest' time to ensure the generated events will not be in the future.

Once the Splunk instance is populated you can then use the sample mode.  My suggestion is to have a large sample, and then use the 'randomizeEvent' and 'count' so that for every X second(s) as specified in the interval, N number of events as specified by count will be generated.  The generated event will be randomized when you set the 'randomizeEvent' to true.  The larger of the data set in your sample, the better it is.

Thank you
