### ISSUE TITLE
Milliseconds and Nanoseconds Not Supported

### ISSUE THREAD

**Issue by dmaislin** [splunk/eventgen#15]
It seems that the strptime options for milliseconds or nanoseconds do not work.

For example:
token.0.token = ^\d{2}/\d{2}/\d{4}\s\d{2}:\d{2}:\d{2}.\d{3}
token.0.replacementType = timestamp
token.0.replacement = %m/%d/%Y %H:%M:%S.%f

Outputs microseconds with no issue:
05/02/2014 07:01:08.934002

If I try this, wanting milliseconds:
token.0.token = ^\d{2}/\d{2}/\d{4}\s\d{2}:\d{2}:\d{2}.\d{3}
token.0.replacementType = timestamp
token.0.replacement = %m/%d/%Y %H:%M:%S.%3N

It outputs 3N instead of a 3 digit millisecond:
05/02/2014 07:09:40.3N

%N is referenced in our docs:   %N	For GNU date-time nanoseconds. Specify any sub-second parsing by providing the width: %3N = milliseconds, %6N = microseconds, %9N = nanoseconds.

http://docs.splunk.com/Documentation/Splunk/latest/Data/Configuretimestamprecognition#Enhanced_strptime.28.29_support

%f seems to be a Python only thing.
%f is not referenced in our docs or in the http://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html also referenced in our docs.

**Comment by coccyx** [comment]
%N is a splunkism.  Not going to mirror the same support.
