### ISSUE TITLE
[BUG] Regression - Running `python ./splunk_eventgen/__main__.py generate splunk_eventgen/README/eventgen.conf.tutorial1` failed

### ISSUE THREAD

**Issue by li-wu** [splunk/eventgen#153]
**Description**
Running `python ./splunk_eventgen/__main__.py generate splunk_eventgen/README/eventgen.conf.tutorial1` for `develop` branch failed.

**To Reproduce**
Directly run `python ./splunk_eventgen/__main__.py generate splunk_eventgen/README/eventgen.conf.tutorial1`. 

**Expected behavior**
Give events output. 

**Actual behavior**
Error throw: 
```
  File "./splunk_eventgen/__main__.py", line 25, in <module>
    EVENTGEN_VERSION = splunk_eventgen_init.__version__
AttributeError: 'module' object has no attribute '__version__'
```

**Sample files and eventgen.conf file**
`splunk_eventgen/README/eventgen.conf.tutorial1`

**Additional context**
This is caused by the the `pep8` pull request here: 
https://github.com/splunk/eventgen/pull/151/files#diff-afc41a2be8638faf5aa07904e026e238R17

When moving `import eventgen_core` to the front which inserts `splunk_eventgen/lib` to the front of `sys.path`. Then the `import __init__ as splunk_eventgen_init` imports `splunk_eventgen/lib/__init__.py` which is not expected.

**Comment by jmeixensperger** [comment]
Tested fix locally with reproduction steps.
