### ISSUE TITLE
[FEATURE/IMPROVEMENT] Format code in CI

### ISSUE THREAD

**Issue by jmeixensperger** [splunk/eventgen#161]
**Is your feature request related to a problem? Please describe.**
Not all checked-in code adheres to the code standards we defined.

**Describe the solution you'd like**
We should start using our recently-added formatting tools (yapf/isort) in the CI to keep our format consistent. Ideally, this should run either on every code check-in, or on a nightly basis.

**Describe alternatives you've considered**
Adding this process into our release scripts: we wouldn't be linting often enough and could introduce bugs dangerously close to release time.

**Additional context**
We've already found bugs after manually formatting the code to our liking.

**Comment by GordonWang** [comment]
This is very important for our code base health. However, I would like to suggest to do this after we finish a bunch of functional end to end test cases to cover the main features.
Then, we may have more confidence when formatting the code in batch.
