### ISSUE TITLE
[IMPROVEMENT] improve the doc section about jinja template tutorial

### ISSUE THREAD

**Issue by GordonWang** [splunk/eventgen#164]
**Is your feature request related to a problem? Please describe.**
In tutorial, some prebuilt magic template vars are not documented for jinja template.
In this page, http://splunk.github.io/eventgen/TUTORIAL.html , as a user, I have no idea what "time_now", "time_now_epoch", "time_now_formatted" means in the template. And I do not know what kind of configuration vars can be defined when I use jinja template, such as earliest, latest, end, interval etc.

**Describe the solution you'd like**
* All the prebuilt template vars should be well explained in the doc and user can learn how to use them.
* clearly explain the configuration parameters which work with jinja template generator

**Describe alternatives you've considered**
N/A

**Additional context**
this is only a document enhancement.

**Comment by lephino** [comment]
I wrote a lot of this in the template: https://github.com/splunk/eventgen/tree/develop/tests/sample_eventgen_conf/jinja

We need to just get this stuff specifically:
https://github.com/splunk/eventgen/blob/develop/tests/sample_eventgen_conf/jinja/templates/test_jinja_timeexamples.template

transferred into a tutorial section.
