### ISSUE TITLE
[BUG] verbose flag does not work in splunk_eventgen cmd line tool

### ISSUE THREAD

**Issue by GordonWang** [splunk/eventgen#175]
**Describe the bug**
client cmd line tool parameter -v/--verbose does not work 

**To Reproduce**
1. use . pip to install eventgen
2. splunk_eventgen -v generate <what-ever-conf-file>

**Expected behavior**
the log level should be debug and all log should be flushed to stderr

**Actual behavior**
get an error in log 
> 2019-04-20 11:03:23 eventgen        INFO     MainProcess Key 'verbose' in stanza 'global' may not be a valid setting
and the log level is info, no debug log 

**Screenshots**
n/a

**Sample files and eventgen.conf file**
any file is ok

**Do you run eventgen with SA-eventgen?**
No

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7
 - OS: macos 10.14
 - Virtual Env is used: yes
 - Eventgen Version 6.3.4

**Additional context**

**Comment by arctan5x** [comment]
Fixed.
