### ISSUE TITLE
[BUG] urlparams is not set properly

### ISSUE THREAD

**Issue by knjkmd** [splunk/eventgen#179]
**Describe the bug**
index, source, sourcetype and hostRegex specified in a config files are not properly set as url parameters for http POST request because of the wrong if conditions.

https://github.com/splunk/eventgen/commit/506a9383aaf39ca43f906492f27f0e1c39aa95ed

**To Reproduce**
1. Install eventgen as a python package
2. Set index, source, sourcetype and hostRegex in a config file
3. Run eventgen

**Expected behavior**
index, source, sourcetype and hostRegex in the pushed events are the same as specified in the config file

**Actual behavior**
Default values are used
index => "main"
host => ip of the sender
source = "http-simple"
sourcetype = "unknown-to_small"

**Do you run eventgen with SA-eventgen?**
No

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7.14
 - OS: Redhat
 - Virtual Env is used: Yes
 - Eventgen Version 6.3.4

**Additional context**
In the commit: https://github.com/splunk/eventgen/commit/506a9383aaf39ca43f906492f27f0e1c39aa95ed, 
"if index != None:" is replaced by "if not index:"

**Comment by li-wu** [comment]
@knjkmd could you provide the `eventgen.conf` as well as the sample file? Thanks.

**Comment by knjkmd** [comment]
I edit the file for tutorial2.
[eventgen_conf.zip](https://github.com/splunk/eventgen/files/3112420/eventgen_conf.zip)

**Comment by li-wu** [comment]
@knjkmd I can reproduce this issue on my local env.  I will fix it later. Thank you.
