### ISSUE TITLE
Backfill of sample data fails when multiple stanza apply to the same file

### ISSUE THREAD

**Issue by coleman07** [splunk/eventgen#18]
I have been trying to load windows data provided by Splunk in the Windows Add on app. When I added the backfill option to eventgen.conf for the Windows Add on app, the data did not backfill. Instead, it replaced the timestamp as if going forward in time. For example, using the configuration file below, I ran eventgen and here is what my data looked like after running for several minutes:

I started eventgen at 3:36 am. When I look at the data in the search app, I see 815 events at 3:31 am, 1455 events at 3:32 am, 1402 events at 3:33, 1530 events at 3:34 and 1476 events at 3:35. So, instead of replacing the timestamp with times from 24 hours prior to running, it is putting them all within 5 minutes of the starting eventgen.

Here is the problem and I offer a solution. When eventgen does its initial configuration in eventgenconfig.py,  for each stanza in the config file, a Sample object is created. When encountering tokens in the config file, a new Token object is created and an attribute of the object is the sample that created the token.

Once all of the file is read, eventgen combines samples to create one sample for each file in the samples directory. These new samples are used to generate data for splunk and it is these new samples where the backfill information is stored. When the multiple samples for a file were combined, the token object's sample was not updated to point to the new sample object thus _getReplacement method didn't know anything about the backfilling since it was looking at an old Sample object.

I fixed the problem by inserting a for loop inside the for loop going through the final samples at line 427. It goes through all the tokens for that sample and changes the sample attribute in the token object to point to the new sample.

for s in tempsamples:
    for t in s.tokens:
        t.sample = s
    if s.mode == 'replay':

This fixes the problem because _getReplacement now knows the current information about the sample.

#### Default replacement for all windows logs
[.*\.windows]
breaker = ^\d{2}\/\d{2}\/\d{2,4}\s+\d{2}:\d{2}:\d{2}\s+[AaPp][Mm]
#interval = 3600
interval = 120
count = 10
earliest = -5m
latest = now
backfill = -1d

[Security\.(528|529|537|539|540|552)\.windows]
## replace @@user
token.0.token = @@user
token.0.replacementType = file
token.0.replacement = $SPLUNK_HOME/etc/apps/SA-Eventgen/samples/dist.all.last

## replace Logon_Type
token.1.token = Logon Type:\s*(.*)
token.1.replacementType = random
token.1.replacement = integer[0:11]

## replace Source Network Address:
token.2.token = Source Network Address:\s*(.*)
token.2.replacementType = file
token.2.replacement = $SPLUNK_HOME/etc/apps/SA-Eventgen/samples/ip_address.sampl
e

## replace Workstation Name:
token.3.token = Workstation Name:\s*(\S*)$
token.3.replacementType = file
token.3.replacement = $SPLUNK_HOME/etc/apps/SA-Eventgen/samples/hostname.sample

[Security.1102.windows]
#interval = 3600
interval = 600
## Generate all events in sample
count = 0

**Comment by coccyx** [comment]
Should be fixed now.
