### ISSUE TITLE
[BUG]when one of the target node is down and httpeventWaitResponse=true, eg throughput falls down

### ISSUE THREAD

**Issue by YifengMao** [splunk/eventgen#201]
**Describe the bug**
set outputMode=httpevent and httpeventWaitResponse=true, configure a list of indexers to receive hec
when one of indexers is down, 
if self.config.httpeventWaitResponse:
                    for session in self.active_sessions:
                        response = session.result()
session.result() takes lots of time to get 'Connection timeout'  in each flush() cycle, and slow down the throughput(in my test, 90% of throughput)

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what happens after doing the reproduce steps.

**Screenshots**

**Sample files and eventgen.conf file**
Please attach your sample files and eventgen conf file

**Do you run eventgen with SA-eventgen?**
Yes/No(No means you run eventgen with pip module mode)

**If you are using SA-Eventgen with Splunk (please complete the following information):**
 - OS: [e.g. Windows/Mac OS 10.14]
 - Eventgen Version [e.g. 22]
 - Splunk Version[e.g. 7.1.3]
 - What other apps you have installed in Splunk etc/apps?

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: [e.g. 2.6]
 - OS: [e.g. Windows10]
 - Virtual Env is used: Yes/No
 - Eventgen Version [e.g. 6.3.2]

**Additional context**

**Comment by jmeixensperger** [comment]
The feature seems to work as expected then, unless I am mistaken. If we want to wait for the responses, we're always going to block the outputter when we flush. We can use a default timeout value or allow the conf files to specify a timeout to use, but I think the easiest fix is simply not waiting for those responses (httpeventWaitResponse=false).

Is there some expected behavior here that I am missing?

**Comment by YifengMao** [comment]
@jmeixensperger i agree it is expected. 
But my point is that, slow respond in one node blocks the throughput in all the nodes (self.active_sessions keeps hec requests to different idxs)

it's really annoying in a splunk deployment with hundreds of idxs because one host is down is a very normal scenario.

The more friendly behavior i think might be:

if an indexer is not available, just remove it from server_list (or do nothing if this indexer is selected in output stage to make data load per idx stable)

just catch Connection Refused or Timeout exception in wait response stage, and exclude the host?

**Comment by arctan5x** [comment]
Makes sense. I will add the functionality to remove the host that is down. Also, if there is no active host, then we will raise an error.

**Comment by arctan5x** [comment]
PR pending.
