### ISSUE TITLE
[BUG] throughput doubled when using multiprocess mode

### ISSUE THREAD

**Issue by YifengMao** [splunk/eventgen#216]
**Describe the bug**
use the standard es bundle, 
run cmd
`splunk_eventgen generate eventgen.conf --multiprocess`
and 
`splunk_eventgen generate eventgen.conf`
with exact the same conf file, multiprocess mode reports 2x throughput

**To Reproduce**
1. pip install splunk_eventgen==6.3.4
2. download es bundle [mixed_all_data_from_customer_for_cs (1).zip](https://github.com/splunk/eventgen/files/3205767/mixed_all_data_from_customer_for_cs.1.zip)
3. edit index and perdayvolume (pick a small perdayvolume so that thread mode won't reach its limit)
4. compare the throughput 

**Expected behavior**
throughputs equals

**Actual behavior**
multiprocess throughput is 2x larger than thread mode throughput
<img width="1438" alt="Screen Shot 2019-05-22 at 13 51 08" src="https://user-images.githubusercontent.com/7123955/58150417-1d01ab80-7c99-11e9-8c25-3619acfa884a.png">

**Comment by li-wu** [comment]
I tried with version 6.3.4 and the latest fixed version, using `thread` and `process` generates the same amount data.  Reopen it if you have this issue again.
