### ISSUE TITLE
eventgen install as app error

### ISSUE THREAD

**Issue by li-wu** [splunk/eventgen#22]
I install the eventgen as an app of Splunk and restart it from terminal. It gives me the message:
>Checking conf files for problems...
>		Invalid key in stanza [source::...eventgen_metrics.log] in >/Applications/splunk/etc/apps/eventgen-dev/default/props.conf, line 12: kv_mode  >(value:  json)
>		Invalid key in stanza [source::...eventgen_metrics.log] in >/Applications/splunk/etc/apps/eventgen-dev/default/props.conf, line 13: >indexed_extractions  (value:  json)
>		Your indexes and inputs configurations are not internally consistent.

But the eventgen works fine, I can get data into Splunk and search the data. 
I do not know it is a bug or some other figure I do not know. 

Thanks.

**Comment by coccyx** [comment]
Can't reproduce.
