### ISSUE TITLE
[BUG] outputWorker configuration does not take effect

### ISSUE THREAD

**Issue by li-wu** [splunk/eventgen#225]
**Describe the bug**
`outputWorker` config does not take effect as the output worker count is fixed to 1.

**Expected behavior**
Output worker count should be consistent with configuration.

**Actual behavior**
Output worker count is fixed to 1.
eventgencore.py:164:
```
self._create_output_threadpool()
```
eventgencore.py:185:
```
    def _create_output_threadpool(self, threadcount=1):
        '''
        the output thread pool is used for output plugins that need to control file locking, or only have 1 set thread
        to send all the data out of. This FIFO queue just helps make sure there are file collisions or write collisions.
        There's only 1 active thread for this queue, if you're ever considering upping this, don't.  Just shut off the
        outputQueue and let each generator directly output it's data.
        :param threadcount: is how many active output threads we want to allow inside of eventgen.  Default 1
        :return:
        '''
        # TODO: Make this take the config param and figure out what we want to do with this.
        if getattr(self, "manager", None):
            self.outputQueue = self.manager.Queue(maxsize=500)
        else:
            self.outputQueue = Queue(maxsize=500)
        num_threads = threadcount
        for i in range(num_threads):
            worker = Thread(target=self._worker_do_work, args=(
                self.outputQueue,
                self.loggingQueue,
            ), name="OutputThread{0}".format(i))
            worker.setDaemon(True)
            worker.start()
```

**If you are using eventgen with pip module mode (please complete the following information):**
 - Eventgen Version: develop branch

**Comment by lephino** [comment]
outputWorker is not an option that should be used in eg 6.  If it's set, it should probably just warn the end user that the option has been ignored.  This is not a bug, and has to deal with how the plugin's load in eg 6.  This queue specifically is for things that need filelocking, and needs to remain as 1 thread / process.  Plugin's that are multithreadable are now ran directly in the generator thread.

**Comment by li-wu** [comment]
@lephino so we should remove the configuration from doc since it is not used anymore?

**Comment by lephino** [comment]
We should probably mark it "depricated" and say it'll be removed in the future.  If we just remove it now, the parser routine I think will get mad at having a key that's no longer used.
