### ISSUE TITLE
[BUG] sample mode in multiprocess will not work if end = 1

### ISSUE THREAD

**Issue by li-wu** [splunk/eventgen#230]
**Describe the bug**
conf:
```
[sample]
sampleDir = ../sample
mode = sample
earliest = -15s
sampletype = raw
outputMode = stdout
end = 1

token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
token.0.replacementType = timestamp
token.0.replacement = %Y-%m-%d %H:%M:%S

token.1.token = @@integer
token.1.replacementType = random
token.1.replacement = integer[0:10]
```

sample:
```
2014-01-04 20:00:00 WINDBAG Event 1 of 12 randint @@integer
2014-01-04 20:00:01 WINDBAG Event 2 of 12 randint @@integer
2014-01-04 20:00:02 WINDBAG Event 3 of 12 randint @@integer
2014-01-04 20:00:03 WINDBAG Event 4 of 12 randint @@integer
2014-01-04 20:00:03 WINDBAG Event 5 of 12 randint @@integer
2014-01-04 20:00:04 WINDBAG Event 6 of 12 randint @@integer
2014-01-04 20:00:05 WINDBAG Event 7 of 12 randint @@integer
2014-01-04 20:00:06 WINDBAG Event 8 of 12 randint @@integer
2014-01-04 20:00:08 WINDBAG Event 9 of 12 randint @@integer
2014-01-04 20:00:20 WINDBAG Event 10 of 12 randint @@integer
2014-01-04 20:00:21 WINDBAG Event 11 of 12 randint @@integer
2014-01-04 20:00:21 WINDBAG Event 12 of 12 randint @@integer
```

Error:
```
2019-06-03 16:50:09 eventgen        ERROR    MainProcess 'JoinableQueue' object has no attribute 'unfinished_tasks'
Traceback (most recent call last):
  File "/Users/lwu/Workspace/Github/eventgen/splunk_eventgen/eventgen_core.py", line 546, in join_process
    ) or self.workerQueue.unfinished_tasks > 0:
AttributeError: 'JoinableQueue' object has no attribute 'unfinished_tasks'
2019-06-03 16:50:09 eventgen        ERROR    MainProcess 
Traceback (most recent call last):
  File "/Users/lwu/Workspace/Github/eventgen/splunk_eventgen/eventgen_core.py", line 362, in _worker_do_work
    item = work_queue.get(timeout=10)
  File "<string>", line 2, in get
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
```

**Comment by lephino** [comment]
am aware of this one; for those that look at this, it's caused by "unfinished tasks" only existing after a process is joined.  The complete join logic has to change, and I've got a few ideas on how to deal with this.  Ping me directly if you decide to try and tackle this.

**Comment by li-wu** [comment]
@lephino , I am wandering if `not self.workerQueue.empty()` and `self.workerQueue.unfinished_tasks > 0` are duplicate judgement here for `eventgen_core.py` line 552.  

I removed `self.workerQueue.unfinished_tasks > 0` and this issue is gone.  And `unfinished_tasks` does not seem to be a public API for Queue object.

**Comment by arctan5x** [comment]
@li-wu unfinished_tasks is not an attribute for the Multiprocess Queue object.

WorkerQueue is a different object depending on the threaded or process mode. In Multiprocess queue, unfinished_tasks needs to be replaced by something equivalent to  unfinished_tasks

**Comment by li-wu** [comment]
@arctan5x In multiprocess mode, `JoinableQueue` is used and `JoinableQueue` is a `Queue` subclass.  I do not think replacing it with something equivalent(and I am not sure what it is) will work.

**Comment by arctan5x** [comment]
https://docs.python.org/2/library/multiprocessing.html#multiprocessing.JoinableQueue
https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Queue

Don't think unfinished_tasks is properly implemented. Running dir on the object will show it clearly.

**Comment by lephino** [comment]
both are kinda wrong, unfinished tasks is an attribute that's created once a process calls "join()".  TLDR, the logic of joining the queue tells process to keep track of unfinished tasks.  The issue that exists is, we run 100% async and never have anything join the async queue.  Leave this bug open a bit, my current plan is to create 1 more thread queue that autojoins a process to each queue to keep track of internal numbers, and then this logic will work, and the parent process won't need to join().  A simple while count > 0 on the unfinished tasks will suffice.   If I can't get this to work, I will create a trigger that will just tell processes / threads to die after all of the threadpool is empty, and then it'll exit once the count hits 0.

**Comment by li-wu** [comment]
Reading the source code of `queue`, I do not think `unfinshed_tasks` should be directly used in code base since it is actually a private variable(Py3) and it is used as Semaphore for synchronize.

**Comment by li-wu** [comment]
> both are kinda wrong, unfinished tasks is an attribute that's created once a process calls "join()". TLDR, the logic of joining the queue tells process to keep track of unfinished tasks. The issue that exists is, we run 100% async and never have anything join the async queue. Leave this bug open a bit, my current plan is to create 1 more thread queue that autojoins a process to each queue to keep track of internal numbers, and then this logic will work, and the parent process won't need to join(). A simple while count > 0 on the unfinished tasks will suffice. If I can't get this to work, I will create a trigger that will just tell processes / threads to die after all of the threadpool is empty, and then it'll exit once the count hits 0.

The proposal you have seems making this more complex...
