### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dataPhysicist** [splunk/eventgen#24]
I'd like to be able to whitelist/blacklist when using token.<n>.replacement. For example, if I''m referencing a file like "allhosts.csv" I want to be able to blacklist a set of hosts with a regex. Possibly an additional parameter like below:
# replace server name

token.2.token = (**SERVERNAME**)
token.2.replacementType = file
token.2.replacement = $SPLUNK_HOME/etc/apps/oidemo/master_eventgen_replace/webhosts.sample:2
token.2.replacementWhitelist.0 = *
token.2.replacementBlacklist.0 = webserver-[0-9]

**Comment by coccyx** [comment]
Totally valid request, but why wouldn't you just modify the source file or create a different copy of it for that token?

**Comment by dataPhysicist** [comment]
I have a few scenarios going at the same time. For example, I need webserver-02 to spike in CPU at 30min past the hour. To do this I create eventgen stanzas and sample files:
- An "issue" sample file which spikes the CPU data at 30min past the hour for webserver-02
- A noise sample for the first 30min of webserver-02 
- A problem sample file(s) which runs for the whole hour that generates cpu data for all hosts replacing SERVERNAME from allhosts.sample which has all hosts except webserver-02.

Next I want to do something similar (say a spike in queries and cpu) for dbserver-02 but now I have to create another file with all hosts except dbserver-02 and non-db servers. 

As I continue to add scenarios I have to make a lot of files. A white/black list allows me to substantially reduce the number of replace files required and makes it easier to update/maintain. 

Make sense?

**Comment by coccyx** [comment]
this is a good idea.  I just don't want to touch that code :).  I'm leaving it open for the time being.

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, please recreate the issue if you still see fit.
