### ISSUE TITLE
[BUG] Tutorial 1 (and presumably similarly formatted eventgen.conf files) hang post-6.3.5

### ISSUE THREAD

**Issue by hexecute** [splunk/eventgen#244]
**Describe the bug**
I'm trying to learn how to use Eventgen, so I look at the docs [1]. I'm trying to run the first tutorial file [2], but nothing happens. There's no stdout output or log output. If I add the verbosity flag, there's output of the initial setup and then nothing. I did some investigation, and the command works from 6.3.0 to 6.3.5, but post-6.3.5, it doesn't work.

I assume this issue also affects similarly formatted files, but I'm unable to figure it out as I'm new to eventgen.

[1] http://splunk.github.io/eventgen/BASICS.html
[2] https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/README/eventgen.conf.tutorial1

**To Reproduce**
1. Install eventgen 6.3.6 or later
2. Run `eventgen -v generate README/eventgen.conf.tutorial1`

**Expected behavior**
I expect eventgen to print to stdout like in 6.3.5.

**Actual behavior**
Nothing happens. There's no stdout output and no log output.

**Sample files and eventgen.conf file**
https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/README/eventgen.conf.tutorial1

**Do you run eventgen with SA-eventgen?**
No.

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7
 - OS: Mac High Sierra
 - Virtual Env is used: Yes
 - Eventgen Version: 6.3.6

**Additional context**
You can Slack me. I work at Splunk.

**Comment by li-wu** [comment]
I fired a [PR](https://github.com/splunk/eventgen/pull/262) to address this issue. Thanks for reporting this.
