### ISSUE TITLE
Is EMBEEDED supposed to be EMBEDDED?

### ISSUE THREAD

**Issue by dmaislin** [splunk/eventgen#25]
./lib/plugins/output/splunkstream.py:                logger.error('Error getting session key for non-SPLUNK_EMBEEDED for sample %s' % self._sample.name)

Also, maybe add a clearer description when you have bad credentials or are missing the splunkPort?  I was a dunce and could not figure out what this error was telling me.

**Comment by coccyx** [comment]
I've grown used to the misspelling, but I'll add some to the description in the error message.

**Comment by coccyx** [comment]
Added an additional error description.
