### ISSUE TITLE
[BUG] Multiple Eventgen service CLI parameters don't work

### ISSUE THREAD

**Issue by hexecute** [splunk/eventgen#253]
**Describe the bug**
There are some CLI parameters described when running `splunk_eventgen service --help`. At least four of these don't work (AMQP_HOST, AMQP_WEBPORT, AMQP_USER, AMQP_PASS). From looking at the code, the bug is with these lines [1, 2]. The connection uses the environment variables and never touches the CLI parameters passed in. Hardcoding this to the correct value in my local code makes this work normally.

[1] https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/eventgen_nameko_server.py#L51-L58
[2] https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/eventgen_nameko_controller.py#L39-L46

**To Reproduce**
1. `splunk_eventgen service --role SOMETHING --amqp-host CENSORED`

**Expected behavior**
I expect Eventgen to connect to the host.

**Actual behavior**
Eventgen complains that it can't connect to localhost.

**Do you run eventgen with SA-eventgen?**
No

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7
 - OS: MacOS High Sierra
 - Virtual Env is used: Yes
 - Eventgen Version: 6.3.5

**Additional context**
You can Slack me. I work at Splunk.

**Comment by li-wu** [comment]
Since we released 6.5.1 and adopted `redis` as message queue the bug is not valid now. Thanks, @hexecute .
