### ISSUE TITLE
[BUG] eventlet and nameko aren't specified anywhere as dependencies

### ISSUE THREAD

**Issue by hexecute** [splunk/eventgen#255]
**Describe the bug**
`eventgen service --role SOMETHING` will fail unless eventlet and nameko are installed. I considered opening a PR, but I'm not sure whether the intention is to add these to docs or add these as requirements during pip installation. Also, I don't know how licensing and version management works with this project. nameko is mentioned in the LICENSE file, but eventlet is not.

**To Reproduce**
1. Install splunk_eventgen
2. Run `eventgen service --role SOMETHING`

**Expected behavior**
I expect the command to work.

**Actual behavior**
An error pops up saying that eventlet can't be found. If you install eventlet, then another error pops up saying that nameko can't be found. If you install nameko, then it works.

**Do you run eventgen with SA-eventgen?**
No

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: 2.7
 - OS: MacOS High Sierra
 - Virtual Env is used: Yes
 - Eventgen Version: 6.4.0

**Additional context**
You can Slack me. I work at Splunk.

**Comment by arctan5x** [comment]
Nameko is completely replaced by a new architecture of Eventgen server.
