### ISSUE TITLE
[BUG] error when generating conf file from a pip installation 

### ISSUE THREAD

**Issue by rfirpo** [splunk/eventgen#271]
**Describe the bug**
Following this tutorial http://splunk.github.io/eventgen/SETUP.html#install have an error when trying to generate a conf file after a pip installation. When running either of 
```
# Invoke python module
$ python -m splunk_eventgen -v generate tests/sample_eventgen_conf/replay/eventgen.conf.replay

# Alternatively, you can use the `splunk_eventgen` alias
$ splunk_eventgen -v generate path/to/eventgen.conf
```
I get the error
```
2019-07-15 16:40:46 eventgen        INFO     MainProcess {'event': 'Logging Setup Complete.'}
2019-07-15 16:40:46 eventgen        INFO     MainProcess {'queue_size': 500, 'event': 'Set generator queue size'}
Traceback (most recent call last):
  File "/Users/rfirpo/venv/py2.7/bin/splunk_eventgen", line 10, in <module>
    sys.exit(main())
  File "/Users/rfirpo/venv/py2.7/lib/python2.7/site-packages/splunk_eventgen/__main__.py", line 348, in main
    eventgen.start()
  File "/Users/rfirpo/venv/py2.7/lib/python2.7/site-packages/splunk_eventgen/eventgen_core.py", line 411, in start
    self.config.stopping = False
AttributeError: 'NoneType' object has no attribute 'stopping'
```

Just skimming the code and looking at the error it seems the EventGenerator class variable  ```self.config``` in eventgen_core.py is not being set.

**To Reproduce**
From the linked tutorial above:

1. pip install eventgen 
```$ pip install git+https://www.github.com/splunk/eventgen.git```

2. generate conf file
```
# Invoke python module
$ python -m splunk_eventgen -v generate tests/sample_eventgen_conf/replay/eventgen.conf.replay

# Alternatively, you can use the `splunk_eventgen` alias
$ splunk_eventgen -v generate path/to/eventgen.conf
```
3. receive error

**Expected behavior**
eventgen.conf is created in target path
**Actual behavior**
this error:
```
2019-07-15 16:40:46 eventgen        INFO     MainProcess {'event': 'Logging Setup Complete.'}
2019-07-15 16:40:46 eventgen        INFO     MainProcess {'queue_size': 500, 'event': 'Set generator queue size'}
Traceback (most recent call last):
  File "/Users/rfirpo/venv/py2.7/bin/splunk_eventgen", line 10, in <module>
    sys.exit(main())
  File "/Users/rfirpo/venv/py2.7/lib/python2.7/site-packages/splunk_eventgen/__main__.py", line 348, in main
    eventgen.start()
  File "/Users/rfirpo/venv/py2.7/lib/python2.7/site-packages/splunk_eventgen/eventgen_core.py", line 411, in start
    self.config.stopping = False
AttributeError: 'NoneType' object has no attribute 'stopping'
```

**Do you run eventgen with SA-eventgen?**
No

**If you are using eventgen with pip module mode (please complete the following information):**
 - python version: Python 2.7.16 :: Anaconda, Inc
 - OS: OSX
 - Virtual Env is used: Yes (same error with python 2.7 venv)
 - Eventgen Version 6.4.0

**Additional context**
Spoke with Tony Lee and he was able to generate a conf file on OSX with eventgen 6.4.0, so it's possible there is something wrong with my environment.

**Comment by li-wu** [comment]
@rfirpo Are you executing the command under the base dir of eventgen?

**Comment by rfirpo** [comment]
Yes i have tried executing within the splunk_eventgen directory and get the same error

**Comment by li-wu** [comment]
I can not re-produce the bug in my local env.

```
# clone the code
$git clone https://www.github.com/splunk/eventgen
# cd to the directory
$cd eventgen
# create venv
$virtualenv venv && source venv/bin/activate
# build and install
$ python setup.py sdist
$ pip install dist/splunk_eventgen-6.4.0.tar.gz
# run the replay conf
$ python -m splunk_eventgen -v generate tests/sample_eventgen_conf/replay/eventgen.conf.replay
```

**Comment by rfirpo** [comment]
Yes that works for me as well! That's not exactly how i reproduced my error (you use a different pip command than i used which is shown on the install guide) but following those steps works for me

**Comment by li-wu** [comment]
Using `pip install git+https://www.github.com/splunk/eventgen.git` to install eventgen, clone eventgen code and run `python -m splunk_eventgen -v generate tests/sample_eventgen_conf/replay/eventgen.conf.replay` works as well. 
```
$ pip install git+https://www.github.com/splunk/eventgen.git
$ git clone git@github.com:splunk/eventgen.git
$ cd eventgen
$ python -m splunk_eventgen -v generate tests/sample_eventgen_conf/replay/eventgen.conf.replay
```

@rfirpo , I am closing this issue. If you encounter this again, feel free to reopen it.
