### ISSUE TITLE
splunkd.log and eventgen.log error messages when using 'outputMode=splunkstream'

### ISSUE THREAD

**Issue by tiny3001** [splunk/eventgen#29]
Trying to replay a CSV file as a splunkstream. The backfill works and events are going into my index as specified in the CSV file, but there seems to be something else breaking in the background.

From eventgen.log:

```
2015-06-15 15:43:00,050 INFO Still backfilling for sample 'sample_data.csv'.  Currently at 2015-06-09 01:14:00
2015-06-15 15:43:00,051 INFO Waiting for workers, limited to 5
2015-06-15 15:43:00,080 ERROR Received bad status from Storm for sample 'sample_data.csv'
2015-06-15 15:43:00,102 ERROR Data not written to Splunk.  Splunk returned <?xml version="1.0" encoding="UTF-8"?>
<response>
  <messages>
    <msg type="WARN">call not properly authenticated</msg>
  </messages>
</response>

2015-06-15 15:43:00,552 INFO Waiting for workers, limited to 5
```

At the same time, splunkd.log is flooded with this:

```
06-15-2015 15:47:58.968 +0200 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /services/receivers/simple: Broken pipe
06-15-2015 15:47:58.974 +0200 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /services/receivers/simple: Broken pipe
06-15-2015 15:47:58.991 +0200 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /services/receivers/simple: Broken pipe
06-15-2015 15:47:58.992 +0200 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /services/receivers/simple: Broken pipe
06-15-2015 15:47:58.997 +0200 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /services/receivers/simple: Broken pipe
06-15-2015 15:47:58.999 +0200 WARN  HttpListener - Socket error from 127.0.0.1 while accessing /services/receivers/simple: Broken pipe
```

If you leave that long enough, splunkd.log finally shows this:
`06-15-2015 15:47:59.320 +0200 ERROR ExecProcessor - message from "python /opt/splunklab/etc/apps/eventgen/bin/eventgen.py" Segmentation fault (core dumped)`

Nasty segfault.

After a minute or so, the process restarts.

The strangest thing is that the indexing continues to my custom index without a problem.

This is my eventgen.conf:

```
[sample_data.csv]
mode = replay
sampletype = csv
backfill = -7d

## this works, but testing splunkstream
#outputMode = file
#fileName = /opt/splunklab/etc/apps/student-sampledata/logs/sample.log
#fileBackupFiles = 10

## this doesn't seem to work
outputMode = splunkstream
splunkHost = localhost
splunkPort = 8089
splunkUser = admin
splunkPass = adminpass

# 'secure' sourcetype
token.1.token = \w+\s\w+\s\d{2}\s\d{4}\s\d{2}:\d{2}:\d{2}
token.1.replacementType = timestamp
token.1.replacement = %a %b %d %Y %H:%M:%S
```

Supporting information:
Splunk 6.2.3
Ubuntu 14.04 LTS
Eventgen zip I downloaded this morning from Github
Pretty much a clean install I did this morning

It kind of looks like eventgen is trying to contact Splunk Storm (based on the error message, at least), but I can't be sure.

I've checked that the firewall is disabled, checked that you can access localhost port 8089 via telnet and a few other things.

Any idea what could be causing these errors? Even though indexing continues?

**Comment by tiny3001** [comment]
Some additional information:

This morning I tested by just putting sample.tutorial1 in my /samples in my app and renaming eventgen.conf.tutorial1 to eventgen.conf.

In other words, running on the tutorial example as per the video.

Still getting the same errors in splunkd.log

**Comment by joshua-ryan** [comment]
I'm getting the same exact behavior.  The backfill going very, very slow.

**Comment by coccyx** [comment]
Grab the dev branch.  use outputMode=modinput, should work better for you.  Will be merging that branch to master soon.

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.
