### ISSUE TITLE
Basic config, not creating any events

### ISSUE THREAD

**Issue by inventsekar** [splunk/eventgen#294]
Hi, The Issue #292 was closed and i am not sure how to reopen it.. hence creating a new issue... 
Detailed info at .. https://answers.splunk.com/answers/768622/eventgen-basic-configuration-but-still-not-generat.html

**Comment by li-wu** [comment]
I can schedule a short meeting with you for this. Send me your available time: lwu@splunk.com

**Comment by inventsekar** [comment]
Hi, As i am on indian standard timezone,(IST)(i assume you are in US timezone), can i still mail you an IST meeting time, pls confirm. thanks.

**Comment by li-wu** [comment]
I am on GMT+8 time zone. I think it should be easy to find a suitable time slot.

**Comment by inventsekar** [comment]
thanks Li-Wu.. mailed you.

**Comment by inventsekar** [comment]
Thanks a lot, Li-Wu, thats a great help. its working now.. i will check the other configs myself, thanks again for your help. Much appreciated.

**Comment by cybersatrix** [comment]
Could you please post the resolution or the issue that you were facing
