### ISSUE TITLE
[FEATURE/IMPROVEMENT] Add syslog header with user-specified hostname

### ISSUE THREAD

**Issue by patriknordlen** [splunk/eventgen#299]
**Is your feature request related to a problem? Please describe.**
In situations where eventgen is configured to emulate that events are originating from a certain host and set to output events as syslog, this is currently not possible, because the host information is not part of the outgoing message.

**Describe the solution you'd like**
Add a configurable behaviour to have eventgen prefix the generated event with an initial RFC3164 compliant header to the syslog message consisting of a timestamp and the user-specified hostname. This will make it possible for receiving syslog servers to pick up the initial host and mark the events as originating from that host instead of from the IP address of the host eventgen runs on.

**Describe alternatives you've considered**
No alternatives that I know of.

**Additional context**

**Comment by patriknordlen** [comment]
PR with suggested solution here: https://github.com/splunk/eventgen/pull/296

**Comment by jmeixensperger** [comment]
Closing this PR since suggested solution was successfully merged in. Feel free to re-open if this issue requires more changes.
