### ISSUE TITLE
Exception for invalid escape character

### ISSUE THREAD

**Issue by bohrasaurabh** [splunk/eventgen#30]
I just downloaded the eventgen and followed the replay tutorial to set up. I am getting the following Exception. can someone help.

06-17-2015 16:07:52.846 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py" Exception in thread Thread-2:
06-17-2015 16:07:52.846 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py" Traceback (most recent call last):
06-17-2015 16:07:52.846 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py"   File "/opt/splunk/lib/python2.7/threading.py", line 808, in __bootstrap_inner
06-17-2015 16:07:52.846 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py"     self.run()
06-17-2015 16:07:52.847 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py"   File "/opt/splunk/etc/apps/eventgen/bin/eventgen.py", line 42, in run
06-17-2015 16:07:52.847 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py"     partialInterval = self.sample.gen()
06-17-2015 16:07:52.847 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py"   File "/opt/splunk/etc/apps/eventgen/lib/eventgensamples.py", line 190, in gen
06-17-2015 16:07:52.847 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py"     sampleLines.append(line['_raw'].decode('string_escape'))
06-17-2015 16:07:52.847 -0400 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/eventgen/bin/eventgen.py" ValueError: invalid \x escape

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.
