### ISSUE TITLE
Non existent oidemo app referenced in the eventgen.bat file

### ISSUE THREAD

**Issue by johners** [splunk/eventgen#31]
The eventgen.bat file used by the eventgen on a Windows Splunk instance references an oidemo app that doesn't exist. Correcting this to SA-Eventgen fixes the issue (assuming you have actually renamed the eventgen app SA-Eventgen).

**Comment by halr9000** [comment]
@johners this is fixed in the dev branch! I highly recommend using it instead of master. We are long overdue for a merge. I think we can close this issue out. @coccyx you want to touch this item? I don't have write access.

**Comment by coccyx** [comment]
I'm preparing for a merge this week.

**Comment by markshao** [comment]
@coccyx , you may forget merge it to the master branch.
