### ISSUE TITLE
[FEATURE/IMPROVEMENT]add an option to switch httpevent/http_metricevent when setup eventgen server with 'setup' REST API

### ISSUE THREAD

**Issue by YifengMao** [splunk/eventgen#319]
**Is your feature request related to a problem? Please describe.**
When I initialize the server, eventgen always set outputMode to 'httpevent' by force. As metric event hec has already enabled from eventgen 6.4, i want to send metric events to splunkd.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. What is the expect behavior of eventgen which can help you to resolve this problem.
add an option to setup API, outputMode. The default value is httpevent so that current clients will not be impacted.  Two values selectable for the option, httpevent or http_metricevent(or more suitable name)

**Comment by arctan5x** [comment]
https://github.com/splunk/eventgen/pull/340

This PR addresses. All you need to do is to pass in "outputMode" key with metric_httpevent
