### ISSUE TITLE
exit status 1: python setup.py egg_info Check 

### ISSUE THREAD

**Issue by stevezeng1976** [splunk/eventgen#327]
Hi,
when I exec command(pip install git+https://www.github.com/splunk/eventgen.git) on centos with splunk 8.0, there is a error prompt:
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Does anybody  encounter the issue? thanks.

BR
Steve

**Comment by li-wu** [comment]
Evetngen 7.0.0 only supports Python3. Check the release notes to set the python version to start Eventgen: https://splunkbase.splunk.com/app/1924/
