### ISSUE TITLE
I want to set http_metrics mode using eventgen controller[FEATURE/IMPROVEMENT]

### ISSUE THREAD

**Issue by Yangxulight** [splunk/eventgen#329]
**Is your feature request related to a problem? Please describe.**
I want to use "metric_httpevent"  Outputmode under eventgen controller-server mode. But the setup api always overwrite outputmode to "httpevent".

**Describe the solution you'd like**
Read the outputmode from post body. We can give it an default value as "httpevent". User can give it a valid value from post body. See code details here : https://github.com/splunk/eventgen/blob/develop/splunk_eventgen/eventgen_api_server/eventgen_server_api.py, line 541.

**Comment by arctan5x** [comment]
https://github.com/splunk/eventgen/pull/340

This PR addresses. All you need to do is to pass in "outputMode" key with metric_httpevent

**Comment by Rhutwi** [comment]
i am getting an error if i use output Mode as metric_httpevent in eventgen.conf.
do we have to define httpeventservers beforehand if we want eventgen data for metrics index
