### ISSUE TITLE
I want to use multi-thread in cluster mode[FEATURE/IMPROVEMENT]

### ISSUE THREAD

**Issue by Yangxulight** [splunk/eventgen#334]
**Is your feature request related to a problem? Please describe.**
Eventgen cluster mode is using multiprocess. It's wasting many CPU resource if I want eventgen server running on a CPU limit(1 core) container. For example, If I set 20 generator workers, there will be 20 process running on the container. But I remember in eventgen 6.4 we are default use multi-thread mode and I want to know how to use mult-thread mode in eventgen cluster mode.

**Describe the solution you'd like**
Provide mult-thread mode for eventgen.

**Describe alternatives you've considered**

**Additional context**

**Comment by li-wu** [comment]
Please change the `entrypoint.sh` and add `--multithread` as you needed.
