### ISSUE TITLE
[BUG] ITSI bundle perdayvolume throughput ~1/3 compared to eventgen 5

### ISSUE THREAD

**Issue by YifengMao** [splunk/eventgen#342]
**Describe the bug**
Throughput of ITSI data generation configure bundle (attached) on an aws i3.4xl host reduces from 350G(eventgen5 multiprocess) to 150G(eventgen latest 7.3 version, standalone server mode + multiprocess)

**To Reproduce**
apply the bundle, set payload_size=756K, interval=20, process_num = 20.
for eventgen latest, run "/usr/bin/python3.7 /usr/bin/splunk_eventgen service --role standalone&"

[issue.tar.gz](https://github.com/splunk/eventgen/files/3813828/issue.tar.gz)

**Comment by arctan5x** [comment]
How are you measuring the throughput? Are you measuring after one day? How are you setting up the receiving splunk instance? Also, perDayVolume sum in the conf is not 350. Are you setting the total volume to 350? Please provide the chain of api calls you invoked.

**Comment by Yangxulight** [comment]
I have try two kind of builds in one container, here is the result on that bundle with the same settings:
1. eventgen latest build on python3.7(7.0.0):                800KB/s,   CPU:  13% usr  86% sys   0% nic   0% idle
2. eventgen build on python2-stable branch(6.5.2):   4.9MB/s,  CPU:  91% usr   7% sys   0% nic   0% idle

Looks like there are too many CPU usage on system level about eventgen python3 version.

**Comment by li-wu** [comment]
This issue has been fixed. Close it.
