### ISSUE TITLE
[BUG] What outputMode really means ?

### ISSUE THREAD

**Issue by rendi7936** [splunk/eventgen#352]
**Describe the bug**
I use EventGen in Splunk to generate a sample log. I use same stanza name ( which refer to sample log name ) but using different outputMode. 

I get the same sample log result after using different outputMode. Question that i want to ask is what the difference of outputMode ?

**Do you run eventgen with SA-eventgen?**
Yes

**If you are using SA-Eventgen with Splunk (please complete the following information):**
 - OS: CentOS Linux 7 (Core) x86_64
 - Browser : Google Chrome
 - Eventgen Version : 7.0.0
 - Splunk Version : 8.0.0
 - Deployment : In Docker but not using Splunk Original Docker Image, i use centos-systemd image

**Comment by li-wu** [comment]
> outputMode = modinput | s2s | file | splunkstream | stdout | devnull | spool | httpevent | syslogout | tcpout | udpout | metric_httpevent

`outputMode` means different destination for the generated events. For example, if you are using `SA-Eventgen` app, the default value for `outputMode` is `modinput`. If you want to output the generated events via HEC endpoint you should use `httpevent` when you are using `Eventgen` as pip module. Hope it helps.

**Comment by roryab** [comment]
Does this mean that some output modes are not available using the SA-Eventgen app, and some are only available using the pip module?

**Comment by li-wu** [comment]
Yes, the default `outputMode` for `SA-Eventgen` app is `modinput` and change not be changed. If you are using Eventgen as pip module, you can use other `outputMode`s.

**Comment by roryab** [comment]
File output seems to work with the app.

**Comment by li-wu** [comment]
Yes, it might work. But the app is designed to ingest data into Splunk using `modinput`. If you want to generate data into file, using pip module might be more suitable.

**Comment by roryab** [comment]
It would be great if this was documented - I spent ages spinning my wheels trying to get syslogout working using the app.
