### ISSUE TITLE
eventgen not generating as well

### ISSUE THREAD

**Issue by phr0zbyte** [splunk/eventgen#36]
Hi team, I've followed the instructions in the video and I do not have any eventsgenerated as well. App permission settings for both eventgen and internaleventgen have been set to Global..

**Comment by mserieys** [comment]
did you remove the # from the eventgen.conf file ?  (wasn't mentioned but is visible)

backfill = -15m
backfillSearch = index=main sourcetype=splunkd

outputMode = splunkstream
splunkHost = localhost
splunkUser = admin
splunkPass = changeme

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.
