### ISSUE TITLE
Introspecting scheme=modinput_eventgen: script running failed (exited with code 1)

### ISSUE THREAD

**Issue by alikat500** [splunk/eventgen#362]
**Describe the bug**
I installed Eventgen as a Splunk app by downloading Eventgen directly from splunkbase.
After restarting Splunk service and logging into SplunkWeb, I noticed the following message:

"Unable to initialize modular input "modinput_eventgen" defined in the app "SA-Eventgen": Introspecting scheme=modinput_eventgen: script running failed (exited with code 1).."

I see see SA-Eventgen App in SplunkWeb.

However, I do not see SA-Eventgen as an input under Settings > Data inputs.

**To Reproduce**
1. Log into Web UI
2. Click on 'messages'
3. I will see the error

**Expected behavior**
per installation instruction (http://splunk.github.io/eventgen/SETUP.html#splunk-app-installation), I should see SA-Eventgen as an input under Settings > Data inputs.

**Actual behavior**
I do not see  SA-Eventgen as an input under Settings > Data inputs.
Also, there is the above mentioned message after Splunk restart.

**Screenshots**

**Sample files and eventgen.conf file**
Please attach your sample files and eventgen conf file

**Do you run eventgen with SA-eventgen?**
No
**If you are using SA-Eventgen with Splunk (please complete the following information):**
 - OS: Windows 10
 - Eventgen Version 6.5.2
 - Splunk Version 8.0.2
 - What other apps you have installed in Splunk etc/apps?
Destinations - An event generating app for a Splunk course

Following is the cont of Splunk\etc\apps directory:

03/07/2020  17:19    <DIR>          .
03/07/2020  17:19    <DIR>          ..
03/06/2020  19:58    <DIR>          alert_logevent
03/06/2020  19:58    <DIR>          alert_webhook
03/06/2020  19:57    <DIR>          appsbrowser
03/06/2020  22:46    <DIR>          destinations
03/06/2020  19:57    <DIR>          introspection_generator_addon
03/06/2020  19:57    <DIR>          launcher
03/06/2020  19:59    <DIR>          learned
03/06/2020  19:57    <DIR>          legacy
03/07/2020  17:19    <DIR>          SA-Eventgen
03/07/2020  13:36    <DIR>          sample_app
03/06/2020  19:57    <DIR>          search
03/06/2020  19:57    <DIR>          SplunkForwarder
03/06/2020  19:58    <DIR>          SplunkLightForwarder
03/06/2020  19:58    <DIR>          splunk_gdi
03/06/2020  19:58    <DIR>          splunk_httpinput
03/06/2020  19:59    <DIR>          splunk_instrumentation
03/06/2020  19:57    <DIR>          splunk_internal_metrics
03/06/2020  19:57    <DIR>          splunk_metrics_workspace
03/06/2020  19:59    <DIR>          splunk_monitoring_console
03/06/2020  19:58    <DIR>          user-prefs
**If you are using eventgen with pip module mode (please complete the following information):**
N/A

Thanks
**Additional context**

**Comment by li-wu** [comment]
Hi @alikat500, sorry for late reply.
I cannot reproduce the issue on the following condition:
1. OS: Windows 10;
2. Splunk: 8.0.2.1;
3. SA-Eventgen 6.5.2;

And I also use this [bundle](https://github.com/splunk/eventgen/blob/develop/tests/sample_bundle.zip) for test. 

Could you double check it? Thanks.

**Comment by alikat500** [comment]
Hi Li, No  problem at all.  I still see the same issue on my Windows 10 setup.
I installed eventgen on Ubuntu without any issues. I will use the Ubuntu install for now to wrap up the course!

Thanks for the response!

**Comment by li-wu** [comment]
Thanks, @alikat500. I will close the ticket. Reopen it if you have further problems.
