### ISSUE TITLE
[IMPROVEMENT] Add Version of httplib2 to requirements.txt

### ISSUE THREAD

**Issue by HKramm** [splunk/eventgen#381]
**Is your feature request related to a problem? Please describe.**
On my system was httplib2 in version 0.9.2 installed. It seems that in this version disable_ssl_certificate_validation=True
does not work. In my case splunkstream did not work with a self-signed certificate.

**Describe the solution you'd like**
Please add the version in the requirements.txt for httplib2. In my case the version 0.17.2 is working correctly.

**Comment by jmeixensperger** [comment]
Enhancement will be included in next release.
