### ISSUE TITLE
Bug in replay when time difference is one day

### ISSUE THREAD

**Issue by coleman07** [splunk/eventgen#39]
I have been trying to replay our license_usage logs rolloversummary entries which occur once a day. I was finding that some days, I would have 5 events when only one should exist. The issue has to do with the incorrect setting of partialInterval if the timediff is precisely 1 day. I changed the calculation found around line 518 in lib/eventgensamples.py to partialInterval = timeDiff.total_seconds() which appears to fix the problem.

I also returned the difference between now and the backfillts when backfillts is > now so it will sleep for the rest of the time instead of sending out one more event when the backfill completed. I wanted one event per day but the last day had 2 since eventgen processes another event before returning to sleep.

**Comment by coccyx** [comment]
Can you send a pull request in the current development branch and we will review?
