### ISSUE TITLE
Replay mode not always writing data

### ISSUE THREAD

**Issue by bohrasaurabh** [splunk/eventgen#40]
I am using the master branch from Apr 1, 2016. I am doing simple replay mode example as described in the video and have noticed that after the first start/restart of splunk, data does not get written for several hours. Also when the data is written sometimes several hundred entries are written and other times less then 10. My sample file is around 17 MB.

![2016-04-15_110517](https://cloud.githubusercontent.com/assets/12942284/14565633/02d07bcc-02fa-11e6-8733-1fce85e84775.JPG)

**Comment by lephino** [comment]
can you send me the sample you're using and the eventgen.conf?  What version of splunk and what OS are you running on?

**Comment by bohrasaurabh** [comment]
For Sample: Its our Firewall logs... let me anonymize few lines and send it over. 

[myserver: SU: / !] splunk version
Splunk 6.3.3 (build f44afce176d0)

[myserver: SU: / !] uname -a
Linux myserver 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[myserver: SU: / !] cat /etc/centos-release 
CentOS release 6.7 (Final)

[eventgen.zip](https://github.com/splunk/eventgen/files/221549/eventgen.zip)

**Comment by bohrasaurabh** [comment]
I upgraded Splunk to 6.4.1 and this issue persists even in this release.

[myserver: SU: / !] splunk version
Splunk 6.4.1 (build debde650d26e)

**Comment by arctan5x** [comment]
Since this issue has been open for a while and we have released new versions 6.x.x of Eventgen, we are closing this issue. Please recreate the issue if you experience the same problem in the latest version.
