### ISSUE TITLE
The navigation bar and main Eventgen view take over other apps' interfaces

### ISSUE THREAD

**Issue by joshwertheim** [splunk/eventgen#42]
The navigation bar, aside from showing my app's name, is completely the same as the Eventgen one. It's also in the special shade of blue that Eventgen uses for its interface. For instance, it shows these options in the navbar:

Eventgen Performance
Eventgen Logs
Search

This is when I'm viewing the following page: http://localhost:1234/en-US/app/my-cool-app/search

On digging deeper, I noticed that the permissions after install are set up in such a way that Eventgen's views/navbar have **Global** permissions, and are set as the default, which seem to be overriding the settings for my app (and likely others' apps as well). 

Changing that permission within the Splunk interface from Global to simply the SA-Eventgen app fixes the issue.

**Comment by coccyx** [comment]
That's not the intended behavior of Splunk itself.  No app should be able to override another app's nav.  You should open a case with support.
