### ISSUE TITLE
Is there a way to replace the username in the entire event with the same username?

### ISSUE THREAD

**Issue by bkogami** [splunk/eventgen#43]
Hi,

I have 2 events. Both events have a user assigned to auid,uid,euid,suid and fsuid. I'd like to randomize the username. In the first and second event, is there a way to change the username per event? For example, in the first event, all the bkogami username would be changed to tesetuser1 and in the second event, all john.ripper would be changed to alice.wonderland.

Let me know if there's a way to do this.

Thanks,
Bruce

Change from:
type=SYSCALL msg=audit(09/28/2016 22:22:10.968:78668) : arch=x86_64 syscall=execve success=yes exit=0 a0=3d8148c860 a1=7fff3ab64de0 a2=7fff3ab67528 a3=13 items=2 ppid=28166 pid=28167 auid=bkogami uid=bkogami gid=bkogami euid=bkogami suid=bkogami fsuid=bkogami egid=utmp sgid=utmp fsgid=utmp tty=(none) ses=2979 comm=gnome-pty-helpe exe=/usr/lib64/vte/gnome-pty-helper key=privileged 
type=SYSCALL msg=audit(09/29/2016 06:33:53.019:33701) : arch=x86_64 syscall=open success=no exit=-13(Permission denied) a0=0x7f5eeecf4260 a1=O_RDONLY|O_CLOEXEC a2=0x7f5eeecf429c a3=0x38 items=1 ppid=1 pid=11519 auid=john.ripper uid=john.ripper gid=john.ripper euid=john.ripper suid=john.ripper fsuid=john.ripper egid=john.ripper sgid=john.ripper fsgid=john.ripper tty=(none) ses=4527 comm=pool exe=/usr/libexec/goa-identity-service subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=open

Changed to:
type=SYSCALL msg=audit(09/28/2016 22:22:10.968:78668) : arch=x86_64 syscall=execve success=yes exit=0 a0=3d8148c860 a1=7fff3ab64de0 a2=7fff3ab67528 a3=13 items=2 ppid=28166 pid=28167 auid=testuser1 uid=testuser1 gid=testuser1 euid=testuser1 suid=testuser1 fsuid=testuser1 egid=utmp sgid=utmp fsgid=utmp tty=(none) ses=2979 comm=gnome-pty-helpe exe=/usr/lib64/vte/gnome-pty-helper key=privileged 
type=SYSCALL msg=audit(09/29/2016 06:33:53.019:33701) : arch=x86_64 syscall=open success=no exit=-13(Permission denied) a0=0x7f5eeecf4260 a1=O_RDONLY|O_CLOEXEC a2=0x7f5eeecf429c a3=0x38 items=1 ppid=1 pid=11519 auid=alice.wonderland uid=alice.wonderland gid=alice.wonderland euid=alice.wonderland suid=alice.wonderland  fsuid=alice.wonderland egid=alice.wonderland sgid=alice.wonderland fsgid=alice.wonderland tty=(none) ses=4527 comm=pool exe=/usr/libexec/goa-identity-service subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=open

**Comment by mhassan2** [comment]
yes will lookup tables

**Comment by mhassan2** [comment]
with*

**Comment by coccyx** [comment]
Yes, in Eventgen you can use a file replacement and have it select the same selection multiple times.  Put a colon after the selector to indicate you want to select from a particular column in the CSV.  In a single column file, you can just select column 1.

```
token.0.token = (bkogami)
token.0.replacementType = file
token.0.replacement = path/to/file:1
```

**Comment by bkogami** [comment]
Awesome!
Thanks. I'll try that out.

**Comment by bkogami** [comment]
Just a little feed back on using the file:1 technique. 

I worked but it was intermittent.
For instance, if I had a section that used file:1, it would replace some of them but it would leave others untouched.

**Comment by lephino** [comment]
Closing this older ticket, please reopen if it's still an issue in 6.2.1
