### ISSUE TITLE
Fails with self-signed certificates

### ISSUE THREAD

**Issue by jchrisos1** [splunk/eventgen#46]
When running eventgen.py with verbosity enabled against my local installation of Splunk, I see that it errors out due to the self singed SSL certificate.  It would be great to enable a command line option to disable cert checking.  In the meantime, you can add this to lib/plugins/output/splunkstream.py:

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by lephino** [comment]
Closing this older ticket, please reopen if it's still an issue in 6.2.1
