### ISSUE TITLE
Generating Events in the future

### ISSUE THREAD

**Issue by dlamb2** [splunk/eventgen#47]
I have configured the eventgen using the below parameters in the eventgen.conf. For some reason I am seeing events created in the future. Is this a bug or did I misconfigure something?

[sampleIIS.txt]
interval = 1800
earliest = -1800s
latest = now
count = 10
randomizeCount = 2
backfill = -30m
backfillSearch = index=test sourcetype=iis_test

outputMode = splunkstream
index=test
host=webiisserv01
source=\Windows\System32\LogFiles\iis.log
sourcetype=iis_test
....

**Comment by lephino** [comment]
that seems like it may be a bug, can you post your entire sample and how you're calling it to run?  Thanks!

**Comment by dlamb2** [comment]
Will this work? If not let me know.
[iis_test.tar.gz](https://github.com/splunk/eventgen/files/590522/iis_test.tar.gz)

**Comment by lephino** [comment]
Closing this older ticket, please reopen if it's still an issue in 6.2.1
