### ISSUE TITLE
Microsoft AD : eventgen combining events in the sample file

### ISSUE THREAD

**Issue by lakshman237** [splunk/eventgen#48]
Greetings
   I have followed the steps, taken exported sample windows AD logs from prod and replayed it in dev env using eventgen and i notice multiple events (rows in csv file) is combined and appearing as a single event in the splunk index.

  Any pointers please?

thanks
Laks

**Comment by asteinsplunk** [comment]
likely need to set props line merge to false

**Comment by lakshman237** [comment]
Thanks asteinsplunk. in the eventgen conf, i tried and it didn't help. However, if i take the sample file and add to splunk via oneshot using proper props.conf, it does work as expected.
