### ISSUE TITLE
Splunk EventGen Not Working

### ISSUE THREAD

**Issue by mcfabrero** [splunk/eventgen#49]
Hi,
I would like to ask for your help on knowing the possible cause of my eventgen not generating any events.
I have followed every detail from the video tutorial and tried all possible ways to make it work, I also tried to reinstall the eventgen a couple of times but I can't seem to find the reason why it is not working.

I have attached the eventgen log for your reference.

[eventgen.txt](https://github.com/splunk/eventgen/files/738243/eventgen.txt)

Your help is greatly appreciated!

Thanks! #41

**Comment by halr9000** [comment]
That text file isn't helpful. Please provide your eventgen.conf or command-line invocation.

**Comment by mcfabrero** [comment]
Hi @halr9000 
Attached is the  eventgen configuration file and the sample data( in csv format) for your reference.
Your help is greatly appreciated.

Thanks!

[Sample data and Config.zip](https://github.com/splunk/eventgen/files/741001/Sample.data.and.Config.zip)

**Comment by halr9000** [comment]
Works fine for me. Probably your setup. 

- Ensure you are running eventgen from the "develop" branch (which is the default).
- Create a new barebones splunk app (from Apps / create)
- Place your eventgen.conf in the default/ folder of this newly created app
- Place your CSV into a samples/ folder under the app base directory
- Restart Splunk

![2017-01-31_11-01-43](https://cloud.githubusercontent.com/assets/18482/22472993/506788e0-e7a5-11e6-99d2-87d8f39ef1e7.png)

**Comment by mcfabrero** [comment]
Hi @halr9000 ,
I got it working but from a different server of Splunk instance. Initially I'm working on Splunk installed in my machine but has no idea why it is not working. 
 Though there is another concern that I would like to consult with. I tried a different sample data but now I'm back at having an issue of not generating events from this new sample data.

From my understanding, I can generate a number of events from different sample data by just configuring the eventgen.conf right? So what I did is just replace the filename( placed the sample data in samples folder) and configure the regex to look for the timestamp to be replace but eventually, it doesn't seem to generate data.
Is there any limitations in splunk eventgen? Do I need to have an input data that has the index, sourcetype, source, _raw and _time columns in csv format?

I'm attaching the configuration file and the sample data for your review. Probably missed something but this is what I have which is not working.

Your help is greatly appreciated.
[add_cart_file.zip](https://github.com/splunk/eventgen/files/750053/add_cart_file.zip)

**Comment by mcfabrero** [comment]
Finally got it right. Found that it is because of Mode used. It is simply because Replay mode doesn't  have the ability to read all timestamp. I think it is advisable to used Sample mode instead. Please free to correct me if I'm wrong :)
