### ISSUE TITLE
Alerting of generated events by certain threshold

### ISSUE THREAD

**Issue by hepterida** [splunk/eventgen#50]
Hello,
do you have any idea how to catch and alert certain events during Event Generator run? Cannot be done by conventional Splunk approach.
Thank you very much,
Kamil

**Comment by halr9000** [comment]
Please elaborate. Do you wish to have an alert fire in reaction to an event which eventgen had created? In other words, are you (1) wanting to simulate an event, and then simulate an alert in response to that event? Or (2) do you want to fire an alert in reaction to how eventgen is operating? 

Hm, perhaps that's irrelevant. Eventgen is creating real indexed events, after all. Alerts are actions tied to a saved search. Once you get the search working (which is trivial), having that fire an alert should be a core Splunk exercise. Nothing special going on with eventgen events once they are indexed. Perhaps this is better addressed as a Q on https://answers.splunk.com/topics/alert.html

**Comment by hepterida** [comment]
Thanks for a quick answer. (1) is the scenario. We generate increments which raises in time and when reach certain value, than alert should be fired (= simulation of reactor dangerous temperature notification). Data is still in search as well as the whole logic, not in an index. Perhaps that approach is not proper. What do you think?

**Comment by halr9000** [comment]
> Data is still in search as well as the whole logic, not in an index

Sorry, I don't understand this sentence. Have you created an eventgen.conf? Is it creating events in Splunk? Are you running eventgen inside of Splunk, or outside via CLI?

**Comment by hepterida** [comment]
Hal, I try to be more precise - we can do alert and index the data, it's trivial. What we need to solve is the alerting above counted, not indexed data during the realtime. And now, while writing this answer I come slowly to the question, if this is something you can help us with...

**Comment by halr9000** [comment]
The challenge that I'm having is understanding if the issue you face is related to eventgen, or not. Please share the exact search and alert you have trouble with. Perhaps these examples would be helpful: https://docs.splunk.com/Documentation/Splunk/6.5.1/Alert/Alertexamples

**Comment by hepterida** [comment]
Finally, we applied different approach and generate the data by running the report with certain search regularly. Let's close this issue. Thank you for your effort and bb.
