### ISSUE TITLE
Event generator wait for at least 1 seconds

### ISSUE THREAD

**Issue by DieterSchmitz** [splunk/eventgen#51]
I use the event generator to import a csv file into Splunk. For us it is important that the events within the csv file will be imported in the same chronological order so we are using mode=replay. 
Each line in the csv file stores a timestamp which is also very important for us. Let's give you an example of what we need:

--- Beginning of the csv file ---

```
"_raw","_time",host,index,source,sourcetype
"2017-02-01 10:17:35.848,System,2905,8296,1199,2683,,771,804,2.72,1.27,1.30,0.28,0,115602,0,2280cfa4-036e-4be3-a058-664b3475213c","2017-02-01 10:17:35.848",RDS-1,index,source,sourcetype
"2017-02-01 10:17:40.848,chrome.exe,5727,4049,1760,1751,chrome.exe,649,180,2.46,2.85,1.84,1.57,0,101549,1,2280cfa4-036e-4be3-a058-664b3475213c","2017-02-01 10:17:40.848",RDS-1,index,source,sourcetype
"2017-02-01 10:17:41.248,chrome.exe,5727,4049,1760,1751,chrome.exe,649,180,2.46,2.85,1.84,1.57,0,101549,1,2280cfa4-036e-4be3-a058-664b3475213c","2017-02-01 10:17:41.248",RDS-1,index,source,sourcetype
```

----------------------------------

In this case the event generator must wait 5 seconds before inserting the second event and 0.4 seconds before inserting the third one. As I mentioned earlier, the time difference is really important for our splunk app.

I've observed that the event generator waits sometimes exactly seconds (or 2 or 3 seconds) before entering new events. Here is a part of the eventgen.log file

--- snip ---

```
2017-02-01 12:43:55,257 DEBUG module='Timer' sample='SampleData.csv': Generation of sample 'SampleData.csv' in app 'testapp' sleeping for 0.001000 seconds
2017-02-01 12:43:55,280 DEBUG module='SplunkStreamOutputPlugin' sample='SampleData.csv': Flushing output for sample 'SampleData.csv' in app 'testapp' for queue 'eventgen'
2017-02-01 12:43:55,839 INFO module='main' sample='null': OutputQueueDepth=1  GeneratorQueueDepth=0 GeneratorsPerSec=0 OutputtersPerSec=0
2017-02-01 12:43:56,259 DEBUG module='ReplayGenerator' sample='SampleData.csv': Generating sample 'SampleData.csv' in app 'testapp'
2017-02-01 12:43:56,260 DEBUG module='Timer' sample='SampleData.csv': Generation of sample 'SampleData.csv' in app 'testapp' sleeping for 0.000000 seconds
```

--- snap ---

In the first line a waiting period of 0.001 seconds was mentioned, which is correct. As you can see in the fifth line, the next time event is one second later. 
This 1 second gap is the reason why our dashboard in splunk shows wrong data.

And just to complete this thread, here is my eventgen.conf:

```
[global]
debug = true
timeField = _time

[SampleData.csv]
sampletype = csv
mode = replay

outputMode = splunkstream

token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}
token.0.replacementType = timestamp
token.0.replacement = %Y-%m-%d %H:%M:%S.%f
```

After taking a look into the python scripts (I am an absolute beginner in python) I found a way so the event generator creates the event with the same time difference as the events in the csv file.
In the file eventgentimer.py line 214

"old" value from the master branch (which waits full seconds):
                        self.countdown -= self.time
                        time.sleep(self.time)

My new value:
                        time.sleep(self.countdown)
                        self.countdown = 0

After this change, the event generator waits exactly the time difference of the events in the csv file.

What do you think about this code change? Is it correct, and if yes: could you please implement the change into the master branch.

**Comment by lephino** [comment]
Closing this older ticket, please reopen if it's still an issue in 6.2.1
