### ISSUE TITLE
Eventgen Results Combine into One Single Event

### ISSUE THREAD

**Issue by mcfabrero** [splunk/eventgen#52]
Hi All,
I have been trying to find the reason and a solution on why the data being generated by eventgen was combined into one single event. One of my sample file has one row of data which seems to be working well, but when I tried to generate a sample data that contains 2 or more rows, apparently all these rows are combined into one single event for one timestamp.

Anyone who can help me on this?

Your help is greatly appreciated.

Thanks!

**Comment by halr9000** [comment]
You should create/review your sourcetype settings for this data just like a core Splunk data onboarding issue. Assuming your data is coming in as a sourcetype of 'foo', then you'll need to, for example, ensure that you have a props.conf setting that looks for this and contains config elements for event breaking, timestamp detection and so on.

This blog post contains a data onboarding cheatsheet which you might find useful: https://www.aplura.com/splunk/splunk-data-onboarding-cheatsheet/

Here is your docs entry point: https://docs.splunk.com/Documentation/Splunk/6.5.2/Data/Configureeventlinebreaking

And lastly, I suggest closing out this issue and if you still need help, no problem, but you'll find a broader audience on Splunk Answers. Here's a suggested tag: https://answers.splunk.com/topics/line-breaking.html

**Comment by mcfabrero** [comment]
Hi @halr9000 ,
Thank you, appreciate your help :)
