### ISSUE TITLE
Backfill of data not working

### ISSUE THREAD

**Issue by mcfabrero** [splunk/eventgen#54]
Hi All,

Need your help on figuring out why backfill setting doesn't work. I need to backfill data for atleast 1 week but I'm not getting the expected results.

I have attached the configuration file and the sample data for your review.

[backfill config file.txt](https://github.com/splunk/eventgen/files/823663/backfill.config.file.txt)

[jbosstest_R.txt](https://github.com/splunk/eventgen/files/823668/jbosstest_R.txt)

Thanks in Advance!

**Comment by halr9000** [comment]
Please define what you mean by "not working" in detail. Is any data generated? Have you tried the backfill search manually?

**Comment by mcfabrero** [comment]
Hi @halr9000,
Yes, there were data generated but time for the generated events shows the current time instead of applying the backfill I provided in eventgen configuration.  
i.e. Eventgen was initially ran at 5:22AM and the events generated contains the same time eventgen was executed. I assume that time for the events generated should be 5:07 right? since that how backfill works? 

Please see attached results( see backfill_test). 

By backfill search you mean including the line
backfillSearch = index= jboss_testindex sourcetype= jboss_sourcetype

in the configuration file right? Yes, I have tried this one but still getting the same result.

I have attached the configuration(configuration file.txt) and the sample file( jbosstest_R) for your review.


Thanks! Appreciate your help.

[configuration file.txt](https://github.com/splunk/eventgen/files/826782/configuration.file.txt)
[backfill_test.txt](https://github.com/splunk/eventgen/files/826783/backfill_test.txt)
[jbosstest_R.txt](https://github.com/splunk/eventgen/files/826784/jbosstest_R.txt)

**Comment by halr9000** [comment]
You got this working with the default index as per #57 ?

**Comment by mcfabrero** [comment]
Turns out _raw from my sample data doesn't have a timestamp included on it. Tried to tweaked the sample file and now it works. Thanks!
