### ISSUE TITLE
Questions on Event Generation Settings

### ISSUE THREAD

**Issue by mpagatpatan** [splunk/eventgen#55]
Hi there!

Currently, I'm trying to figure out if I can control and modify the index time ( _time) of an event. I have tried to use:
1. Delay - I am unable to generate events using delay command. It is also not stated in the Spec if the integer that will be used would correspond to second/s or minute/s.
2. Earliest and Latest - I am able to generate an event but the index time is still the current time. i.e. earliest = -1800s
latest = -1500s

Do you have other configuration settings you could share that can control the time an event is indexed?

Looking forward to your responses.

**Comment by halr9000** [comment]
`delay` is seconds. Corrected the spec.

Regarding the time, check out the tutorial, or search the repo for `earliest`, you'll find several examples.

**Comment by mpagatpatan** [comment]
Thanks @halr9000 !
