### ISSUE TITLE
Event Generation Settings not working on a Custom Created Index

### ISSUE THREAD

**Issue by mpagatpatan** [splunk/eventgen#57]
Good day dear EventGen SMEs -

In reference to my last post (Issue#55 I believe), I am trying to control the output timestamp (a certain range i.e.  from 5 to 3 hours ago) of an event from EventGen using "earliest" and "latest" commands.

I am unable to make it work on a custom index I created using Settings > Indexes > New Index.

However, when I tried to use it on the "main" index, it magically worked! I was able to limit the time range of the event's timestamp.

Is there a necessary setting needed to be done to make it work as well on other indexes?

P.S. I made sure that there settings under Settings > Indexes are the same and have also tried to use "index = <index name>" in the conf file (although i already read that the index command only works for splunkstream).

eventgen.conf
[internal_eventgen.csv]
disabled = false
mode = sample
sampletype = csv
earliest = -3h
latest = -2h
outputMode = modinput

**Comment by mpagatpatan** [comment]
Additionally, what I used on main index are the exported events from _internal from the Tutorial Video.

I created my own events inside a csv file. There may be further configurations needed to be done a custom index and custom sourcetypes?

**Comment by halr9000** [comment]
As the spec says, outputmode=splunkstream would be required to make this work.

**Comment by mpagatpatan** [comment]
Thanks @halr9000 

It has now worked by adding a timestamp on the _raw column of the csv file.
