### ISSUE TITLE
Process eventgen_modinput.py does not end after splunk shut down

### ISSUE THREAD

**Issue by DieterSchmitz** [splunk/eventgen#68]
On our Ubuntu 16.04 system we've installed Splunk's event generator. After shutting down Splunk, a quick look into the process list shows, that the process `python /opt/splunk/etc/apps/eventgen-master/bin/eventgen_modinput.py` is still running.
After a start and another stop of Spunk, a second process of the one mentioned above is running in the background. With every restart another ghost process exists.

Can anybody reproduce this behavior?

**Comment by gruhby** [comment]
Maybe [this - see: answers.splunk.com](https://answers.splunk.com/answers/261159/python-eventgenpy-process-not-killed-when-stopping.html) is the solution to your problem?

**Comment by DieterSchmitz** [comment]
Thank you very much, gruhby! That solved the issue.
