### ISSUE TITLE
Allow override of properties on the command line

### ISSUE THREAD

**Issue by adrianhall** [splunk/eventgen#7]
I'd like the ability to override stanzas on the command line.  Combine this with Issue #6 to provide a better eventgen debug environment:

i.e. 

python eventgen.py default/eventgen.conf --stanza sp-iisupload.csv --property outputMode=file --property fileName=/tmp/output.log

**Comment by coccyx** [comment]
I allowed some of hte properties without going full bore.  You can check out the current dev branch and see if overriding outputMode and a few others is sufficient.
