### ISSUE TITLE
host.replacement setting doesn't seem to work

### ISSUE THREAD

**Issue by dlamb2** [splunk/eventgen#70]
The host.replacement setting doesn't seem to work, and when applied to the eventgen.conf under a stanza it seems to prevent the events from generating at all. Unless I am misunderstanding how it used. How, when and where does it get implemented? The doc doesn't clarify.

**Comment by lephino** [comment]
Can you paste me your stanza so I can see what all you're doing?

I'm not sure you'll need to use host.replacement, but it requires the host.token, so you'll put a regex in your event that will match what ever field you want to replace, and then you'll use the replacement to specify how you want it replaced.

**Comment by coccyx** [comment]
For what it's worth, it's a pretty hacky feature. I believe it only works with file based replacements. In Gogen, I designed around this by making every field a potential target for token replacements, so all options are available for all fields, host is just one of the fields. If it's a requirement, you may find more success with Gogen for this particular problem.

**Comment by dlamb2** [comment]
Thanks guys. I’ll take a lot at GoGen. I am building out a demo environment and really just want to have better host representation when using multiple TAs.

Dorian Lamb
Sales Engineer
Splunk Inc.
Office: 972-905-2346
Mobile: 214-449-4853
Email:   dlamb@splunk.com<mailto:dlamb@splunk.com>
Plano | San Francisco | Cupertino | London | Hong Kong | Washington D.C. | Seattle | Singapore | Munich | Tokyo

This message is intended only for the personal, confidential, and authorized use of the recipient(s) named above. If you are not that person, you are not authorized to review, use, copy, forward, distribute or otherwise disclose the information contained in the message.
