### ISSUE TITLE
Replay mode with real-time timestamps

### ISSUE THREAD

**Issue by GregorioCunha007** [splunk/eventgen#72]
Can Replay mode produce data with the current time ? Supose my data is from a week ago, no matter how I modify the .conf file, the data eventgen generates is also from that same previous week. Is what I am asking achievable, or I have to change to sample mode ? 

Thanks in advance

**Comment by lephino** [comment]
Replay mode was changed quite a bit in 6.1 and now can replay events in order with new time points.  Just make sure you set your timefield correct.
