### ISSUE TITLE
How to increase number of events generated by Eventgen

### ISSUE THREAD

**Issue by paybsiks** [splunk/eventgen#74]
Hi, I want to increase the events generated by the eventgen app, for example 50k events per minute how can I do this, what config do I need to use. Below is my eventgen.conf feel free to correct me or if theres anything you can suggest kinldy share it to me thanks.

[sample_logs.csv]
mode = sample
sampletype = csv
timeMultiple = 1
backfill = -10m
backfillSearch = index=perf_index sourcetype=st_sample_logs

outputMode = splunkstream
splunkHost = localhost.localdomain
splunkUser = admin
splunkPass = changeme

token.0.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3,6}
token.0.replacementType = timestamp
token.0.replacement = %Y-%m-%d %H:%M:%S,%f

token.1.token = \d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}.\d{3,6}
token.1.replacementType = timestamp
token.1.replacement = %m-%d-%Y %H:%M:%S.%f

token.2.token = \d{2}/\w{3}/\d{4}:\d{2}:\d{2}:\d{2}.\d{3,6}
token.2.replacementType = timestamp
token.2.replacement = %d/%b/%Y:%H:%M:%S.%f

token.3.token = \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}
token.3.replacementType = timestamp
token.3.replacement = %Y-%m-%d %H:%M:%S

token.4.token = \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}
token.4.replacementType = timestamp
token.4.replacement = %Y-%m-%dT%H:%M:%S

**Comment by lephino** [comment]
add "count=50000" after mode.

**Comment by paybsiks** [comment]
I've added the count=50000 after mode but does not work well, it does not generate the expected amount of events 50k per minute. is there any possible solution to increase the event count?

Thanks in advance

**Comment by lephino** [comment]
Just pushed the eg 6.1 version which has several improvements / changes.  Can you try your eventgen.conf on 6.1 and let me know how it works for you?

**Comment by arctan5x** [comment]
Latest version is 6.2.1. Please try it out and see if the problem continues.
