### ISSUE TITLE
Can we replay a json sample file with eventgen.conf to show current timestamp?

### ISSUE THREAD

**Issue by lakshman237** [splunk/eventgen#75]
What config is needed to simply replay a sample json file, but replace the timestamp with current timestamp, so as to have continuous stream of events?

I tried with mode=replay and the it generates the files with the timestamp as in the sample file. It doesn't change timestamp as per timestamp formating

**Comment by halr9000** [comment]
That's the purpose of replay mode. I would double-check your syntax, especially the timestamp regex. If you paste your .ini files and a sample of the data, we can maybe find the issue.

https://github.com/splunk/eventgen/blob/develop/documentation/TUTORIAL.md#the-configuration-file

**Comment by lakshman237** [comment]
Any chance of review?

**Comment by lephino** [comment]
//eventgent.conf

[myalerts.txt]
sampleDir = /opt/splunk/etc/apps/myapps/samples/
mode = replay
#timeMultiple = 1
outputMode = file
fileName = /tmp/myapp_alerts.log
#outputMode = splunkstream
#maxQueueLength = 5
interval = 60
backfill = -15m
backfillSearch = index="myapps_index" sourcetype="mysourcetype"

#TIME_FORMAT = "end": "2018-04-10T09:55:43.132Z"
token.0.token = end\":\s\"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z\"
token.0.replacementType = replaytimestamp
token.0.replacement = %Y-%m-%dT%H:%M:%S.%fZ
