### ISSUE TITLE
VIDEO tutorial is outdated

### ISSUE THREAD

**Issue by kerkael** [splunk/eventgen#76]
Hin I tried to follow the tutorial, but it seems everything has changed in the folders since it was created.
There is now a downloadable eventgen-develop.zip, which contains : 
- some setup files and a splunk_eventgen folder
The splunk_eventgen folder contains : 
- some setup files, samples, and a splunk_app folder
The splunk_app folder seems to be a the app we really need to install to have this work, but ...

So ... if I only need this subfolder to have the eventgen work, why do I need to download the eventgen-develop.zip and the splunk_eventgen ???

The tutorial is not that nice if we have to find out what to do before :(

**Comment by arctan5x** [comment]
Hi,

The whole repository is a pip project folder for Eventgen. Eventgen as a Splunk App is a fraction of the package we offer. As you might have noticed, the subdirectory splunk_app does not contain everything you need. We use it to support a "build command" which will conveniently build a .spl package for you.

Download this whole repo and on the top level directory, run "python -m splunk_eventgen build --destination YOUR_LOCAL_PATH". This will output .spl file that is directly installable to your Splunk.

Let us know if you run into any other issues.

**Comment by kerkael** [comment]
Hi, thanks for the help. Indeed the python command creates a .spl, which is the same as the one I can download from the splunkbase website : sa_eventgen0.6.1. 
Then then video tutorial mentions how to extract events from a running instance from the _internal index, add them into a new app, and have them treated with the eventgen.conf.tutorial1 renamed as eventgen.conf in a local subfolder from the new app.
However, after restarting, no events are visible, but I get this error message : 
Unable to initialize modular input "modinput_eventgen" defined inside the app "eventgen": Introspecting scheme=modinput_eventgen: script running failed (exited with code 1).
01/05/2018 à 18:42:49
And as this script does not have the same name as the one depicted in the tutorial, that's why I say the video is not related anymore to what the github site presents.
I'm still working on this, and I may try other tutorial2,3,4 file, but the problems seems to come from the python script.
I'm using a version 7.1 on a centos linux.
Regards

**Comment by kerkael** [comment]
Hi. The outdated tutorial video (Dec 2012 !!!) is pointed in a link in eventgen/README/Tutorial.md, just after the Welcome introduction. This link [Get Started with the Eventgen!](http://youtu.be/9S-ZeGEfRKg?hd=1) should be removed. It's a Youtube video that could still be accessed from a search engine.

**Comment by arctan5x** [comment]
Got it. Thanks.

**Comment by arctan5x** [comment]
The change will be reflected in the next release.
