### ISSUE TITLE
Cannot generate events in splunk with EventGen

### ISSUE THREAD

**Issue by luckyteos** [splunk/eventgen#77]
Hi there,

I just started trying out EventGen, and am following the tutorial from youtube but can't get any events to generate in splunk. The error I get in splunk is "Unable to initialize modular input "modinput_eventgen" defined inside the app "SA-Eventgen": Introspecting scheme=modinput_eventgen: script running failed (exited with code 1).". I have looked through the issues section and online but I still can't find a solution to this issue. Any help would be much appreciated. Thanks :)

[eventgen-stuff.zip](https://github.com/splunk/eventgen/files/2079421/eventgen-stuff.zip)

**Comment by lephino** [comment]
Can you tell me what version you're using?

**Comment by lephino** [comment]
I also see you're using "replay" but you don't have a "replaytimestamp" set, make sure you have one that specifies the time field and where it's at.

**Comment by luckyteos** [comment]
Also I tried out your suggestion, but I think maybe I am not getting the date format correct. Maybe you could advise me as to how you would change the config file to make eventgen generate events? The other error I am getting <error><message>Splunkd daemon is not responding: ('Error connecting to /services/shcluster/config/config: [Errno 10054] An existing connection was forcibly closed by the remote host',)</message></error>. Thanks in advance :)

[eventgen-debug.zip](https://github.com/splunk/eventgen/files/2082656/eventgen-debug.zip)

**Comment by luckyteos** [comment]
Hi there, 

I managed to get EventGen to generate events with the sample tutorial eventgen.conf file provided, though using an earlier version of eventgen -Version 4.0.0. Though I still like to know how I could do it with the latest version 6.0+. Many thanks for any help in advance :)

**Comment by lephino** [comment]
Your regex won't match your timestamp.  I'll shoot you back a sample in a bit.

**Comment by lephino** [comment]
[luckyteos_eventgen_samples.zip](https://github.com/splunk/eventgen/files/2086236/luckyteos_eventgen_samples.zip)
Let me know if you have any questions

**Comment by lephino** [comment]
btw, just install that as a splunk app, and set it to "global" on permissions, then you'll see your time replayed.

**Comment by luckyteos** [comment]
Hi lephino,

Thanks for your help, the app that you gave me is indeed generating events. Though I still have a question, the events generated by replaytimestamp are not that of the current date and time, but instead of the time in the sample file right?

**Comment by lephino** [comment]
Yeah, you need another token added of type "timestamp" and then it'll replace in the event with the current _time.  Basically, it's a 2 step process, 1 to tell eventgen how to parse the timestamp, and a 2nd to tell eventgen how you want it to look when it exports it.  I suppose this is kinda redundant and maybe we should just open a feature request to replace it all with "replaytimestamp"

**Comment by luckyteos** [comment]
Hi lephino,

Another question came to my mind. While using Eventgen 4.0.0 and following the instructions in the youtube tutorial, like using the eventgen.conf.tutorial1 file and renaming it to eventgen.conf, before then placing the eventgen.conf in the test splunk application I created, there was no issue with timestamp. However, you are saying that in 6.2.1, the same does not work because the timestamp does not match? I am a bit confused as to what this means. I have looked at the two configuration files (the one in the README folder and the one you sent me earlier) and realized the mode is different. Is it true that for 6.0.0 the tutorial file has to be modified to switch the mode from stdout to modinput to get it to work (as in not throwing the error)? Thanks in advance, and for your help thus far :)

**Comment by lephino** [comment]
There were several bugs / changes around timestamps in replay / normal over time, and that's where replaytimestamp was bread out of.  6.0 settles on a true meaning of it.  Long story short, lets call it an evolution of the tool.  There have also been changes on default modes and outputters. So while all the features in eventgen 6 exist, and all older eventgen.confs features that were used should be availible, it does not mean you won't need to updated some stanzas between versions.  We're also trying to push for more clarity on these definitions and we're updating the gitbooks / docs as we go along.

**Comment by luckyteos** [comment]
Hi lephino, thanks for your reply. Looking forward to greater clarity on the new definitions in the documentation :)
