### ISSUE TITLE
Backfilling normal and incident data with eventgen

### ISSUE THREAD

**Issue by alvinkwong47** [splunk/eventgen#82]
I am using eventgen version 6.2.1 in Splunk. Currently, I am using two sets of stanza for generating normal and incident data without overlap by minuteOfHourRate so that the incident will happen every 10 minutes. 

For some reason, I need to backfill one hour of data every time I startup Splunk. However, I found that either only the normal data or the incident data will be backfill in Splunk, depending on the time the Splunk starts. Is there any way I can generate the events so that it follows the pattern that every 10 minutes an incident will occur?

Below are my current configuration,

eventgen.conf
`[global]
disabled = false
debug = true
verbose = true
maxIntervalsBeforeFlush = 1

#####################################
#####################################
[normal.sample]
mode = sample
interval = 10
sampletype = raw
index = test
earliest = now
latest = now
sourcetype = _json
minuteOfHourRate = { "0": 1, "1": 1, "2": 1, "3": 1, "4": 1, "5": 1, "6": 1, "7": 1, "8": 1, "9": 0, "10": 0, "11": 0, "12": 1, "13": 1, "14": 1, "15": 1, "16": 1, "17": 1, "18": 1, "19": 0, "20": 0, "21": 0, "22": 1, "23": 1, "24": 1, "25": 1, "26": 1, "27": 1, "28": 1, "29": 0, "30": 0, "31": 0, "32": 1, "33": 1, "34": 1, "35": 1, "36": 1, "37": 1, "38": 1, "39": 0, "40": 0, "41": 0, "42": 1, "43": 1, "44": 1, "45": 1, "46": 1, "47": 1, "48": 1, "49": 0, "50": 0, "51": 0, "52": 1, "53": 1, "54": 1, "55": 1, "56": 1, "57": 1, "58": 1, "59": 1 }
backfill = -1h

token.0.token = "time":(\d+)
token.0.replacementType = timestamp
token.0.replacement = %s

token.1.token = "temp":"(\d+).0"
token.1.replacementType = random
token.1.replacement = integer[25:28]

#####################################
#####################################
[incident.sample]
mode = sample
interval = 10
sampletype = raw
index = test
earliest = now
latest = now
sourcetype = _json
minuteOfHourRate = { "0": 0, "1": 0, "2": 0, "3": 0, "4": 0, "5": 0, "6": 0, "7": 0, "8": 0, "9": 1, "10": 1, "11": 1, "12": 0, "13": 0, "14": 0, "15": 0, "16": 0, "17": 0, "18": 0, "19": 1, "20": 1, "21": 1, "22": 0, "23": 0, "24": 0, "25": 0, "26": 0, "27": 0, "28": 0, "29": 1, "30": 1, "31": 1, "32": 0, "33": 0, "34": 0, "35": 0, "36": 0, "37": 0, "38": 0, "39": 1, "40": 1, "41": 1, "42": 0, "43": 0, "44": 0, "45": 0, "46": 0, "47": 0, "48": 0, "49": 1, "50": 1, "51": 1, "52": 0, "53": 0, "54": 0, "55": 0, "56": 0, "57": 0, "58": 0, "59": 0 }
backfill = -1h

token.0.token = "time":(\d+)
token.0.replacementType = timestamp
token.0.replacement = %s

token.1.token = "temp":"(\d+).0"
token.1.replacementType = random
token.1.replacement = integer[30:40]`

normal.sample
`{"temp":"23.0","ip":"192.168.1.101","time":1528092000}
{"temp":"23.0","ip":"192.168.1.102","time":1528092000}`

incident.sample
`{"temp":"23.0","ip":"192.168.1.101","time":1528092000}
{"temp":"23.0","ip":"192.168.1.102","time":1528092000}`

**Comment by lephino** [comment]
Backfill was broken in eg 6, and hopefully is fixed in 6.3, look for it soon!

**Comment by arctan5x** [comment]
Interval of 10 would mean 10 seconds interval :)

**Comment by lephino** [comment]
Is this still an issue?

**Comment by lephino** [comment]
Closing this, feel free to reopen if you still have a problem.
