### ISSUE TITLE
SplunkBase installation instructions don't match the tarball provided

### ISSUE THREAD

**Issue by caitelatte** [splunk/eventgen#83]
The [SplunkBase page for eventgen](https://splunkbase.splunk.com/app/1924/#/details) points to the [documentation directory](https://github.com/splunk/eventgen/tree/develop/documentation) in this repository, which recommends running `setup.py` and setting the app up as a Pip package.

However, the tarball I downloaded from the SplunkBase site didn't include any `setup.py` file.

Please either provide instructions on the SplunkBase Details page on how to use the tarball provided, or change the structure of the tarball distribution to match existing documentation.

The setup instructions talk about installing a tar.gz file with pip, so I tried that with the tarball downloaded. Running `pip install eventgen-621.tar.gz` returned the following error, reflecting that there is no `setup.py` file in the tarball file:

```
pip install eventgen_621.tgz 
Processing ./eventgen_621.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/anaconda3/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/9b/09zm299n2137b28vmlh98x7r0000gn/T/pip-req-build-15cj2tk7/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9b/09zm299n2137b28vmlh98x7r0000gn/T/pip-req-build-15cj2tk7/
```

**Comment by lephino** [comment]
Eventgen is currently using python 2.7, we currently do not support python 3.

**Comment by caitelatte** [comment]
Thanks @lephino - I also tried the pip instal with pip2 on my system and received the same error. My problem is more about finding instructions for installing the tarball provided on SplunkBase.

This issue is about the documentation provided in the Splunk App page on SplunkBase, which points to the documentation in this repository, even though they have different installation processes.

I just found a related issue at #76 with comments differentiating between the Splunk App distribution and the developer instructions in this repo, I'll continue reading through them for an answer.

**Comment by lephino** [comment]
The spl on splunkbase just needs to be installed directly into splunk.  You simply go in to your splunk frontend, choose install from file on the app management pane and select the eventgen download.

**Comment by caitelatte** [comment]
@lephino ha, that's much simpler than it seemed from the instructions! Thanks for the very quick help. I hope the complicated instructions on the [SplunkBase page](https://splunkbase.splunk.com/app/1924/#/details) can be updated to prevent future confusion :)

**Comment by lephino** [comment]
lol yeah I'll see about getting those fixed.  The pip install is a reference to this actual repo, and for installing eventgen from this source repo
