### ISSUE TITLE
Not working, but few clues

### ISSUE THREAD

**Issue by JohnKruse** [splunk/eventgen#85]
I've had great success with Eventgen in the past, but recently I've had problems with 6.2.1 on a Mac. This all started when I updated from Splunk 6 to 7. I've blown away my Splunk install and have tried multiple different 7.x versions. Eventgen seems to start. Modinput_eventgen.log has entries and I can see Eventgen in settings/data input, but no eventgen.log is ever started - thus, I'm not sure what to look at. I've tried both the sample data sources and others. I've reinstalled several times with no success.

**Comment by lephino** [comment]
Just to clarify, eventgen on splunk 7, you've gone to "Settings > Data Inputs > Eventgen Mod Input" and made sure to hit "Enable" on it.  You also have TA's set to "GLOBAL".  Eventgen.log is now basically 3 logs, all placed in _internal.  You can actually just search them in splunk by doing: "index=_internal source=*eventgen*.log"

**Comment by lephino** [comment]
I also want to make sure you installed the eventgen from splunk base, or you downloaded this git repo and used the "build" command to create the SPL file that goes inside of splunk

**Comment by JohnKruse** [comment]
Thanks Brian. I think my problems were two-fold. First, my company started
using SPlunk to monitor our laptops. For months, it didn't seem to
interfere, but I think now that something changed and there were conflicts
with port 8089. I went into SA-Eventgen's eventgen.conf and changed the
management port. The second issue was that I don't remember ever having to
enable anything under the Data Inputs... it just worked in the past. So, it
seems to be generating events now.

THanks for your help!
John
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by lephino** [comment]
Understand John, to the point about "The second issue was that I don't remember ever having to
enable anything under the Data Inputs...", you're correct, it used to be enabled by default.  We had several customers accidentally send "eventgen" to a clustermaster, and would have an enabled modinput be pushed out to their indexers.  Eventgen 6 is the first time we've changed to having the modinput disabled by default.  As to the port issue, eventgen shouldn't be requiring any ports, so I'm not quite sure what you have going on there.

**Comment by JohnKruse** [comment]
Thanks Brian. To be more specific, I wasn't able to run Splunk with the the
management port at 8089 as somehow my company's IT shop was binding that
port. So, I changed it to run on 8090. Then Eventgen wasn't working. In the
eventgen.conf file, there was a line *splunkPort = 8089*, so I changed it
to 8090 thinking that it was likely looking to align with the management
port.

Say, I've run into another snag. All of my old data sources used to be set
up on a 10 min cycle for replay purposes. Now, the events are not spaced
out per the original times embedded in each line, but all of them are
pretty much dumped within a second or so every 9 min. I thought that on
Replay, Eventgen was just reading thru the input file and parsing the time
and replaying with the same breaks between events as originally
experienced. This is happening with every Replay source. As a test, I shut
them all down and tried the included "sample.tutorial1" to see if I'd get
the same behavior. I changed the *timeMultiple = 1*, but otherwise left
everything alone. It seems to be doing the same thing every 16ish min. I
took a quick look and it seems that the events are spread over 15 min in
tutorial1. There also seem to be far more events than the 2019 lines in the
sample file.

*Any idea why Replay would be doing these big dumps on the approximate
periodicity of the entire file? *I never had to set anything special to get
this working and I'd assume that the tutorial1 files would work without any
fuss.

Thanks, John

[image: Screen Shot 2018-08-27 at 12.07.42 PM.png]
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by lephino** [comment]
in eventgen 6 we clarified the meaning of "replaytimestamp" and changed the old logic of trying to "guess" which timestamp to actually use for event spacing.  Chances are your samples don't have a token with "replaytimestamp" in eventgen 6, and you just need to update the sample with the proper token / regex for your timestamp.  Let me know if you hit more issues on that.

**Comment by JohnKruse** [comment]
Thanks Brian! That fixed my Replay sources, but now I have a question about
Sample sources.

In the past, I just set the *interval=X* and then would make sure there was
a field (e.g., a random integer) that would ensure each event was unique so
that Splunk wouldn't just ignore the events as redundant (I have a
predictable cycle of events for my testing). Has something changed with
that too? Each one of the Sample sources seems to execute when I first
restart Splunk, but then they seem to ignore my set interval.

I wouldn't keep bothering you, but frankly, the documentation and examples
on Github don't put the changes that have been made front and center. For
instance, only in Tutorial4 is "replaytimestamp" used, and it isn't really
featured in critical pages (e.g., the Configuration File section in
Tutorial.md). Basics.md also point to the old Clint Sharp Youtube video
that doesn't mention it. I am afraid that I'm missing another simple
setting that might have changed.

Thanks much, John


============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by lephino** [comment]
interval = how long to sleep to repeat the selection in seconds.  Meaning everytime you run a sample, there is a random selection of events out of the total number of events in sample mode.  Interval will just dictate how frequently to do it.  So if you have 2 events in your "sample" file, each time "interval" is called, eventgen will randomly select "count" out of that sample.  So if you set "count=1", you'd have a 50/50 shot of getting event 1 or event 2.  Set interval to 10, you have a 50/50 shot of getting event 1 EVERY 10 seconds, meaning by upping interval, you weren't decreasing the chance of seeing duplicate events, your just lowering/raising the cycle of selection.  Adding a higher count, will ALWAYS reduce the chances of selecting the same event, as it's not allowed to reselect the same event UNTIL every event has been used once.  So if your sample has 2 events, and you said "count=3", you're guaranteed that each event in the sample will be used 1 time, and 1 will be used twice.  Setting count to 0 will just cause sample mode to dump the entire sample every interval.  Hope that answers that question (and this logic really hasn't changed at all, it's much better about it's selection, and does things faster, but the same basic concept exists in eg5 and eg6)

Yeah I hear you about replaytimestamp.  It's actually something that's "only" mentioned in the spec files, as it was added over time (I want to say in eg5???) and quite frankly, the docs were never updated.

We're working a lot on the tutorials and docs just due the sure amount of questions we've gotten.  Don't feel bad, it's what i'm here for :D  Clint's video is definitely outdated, and I'll probably remove the link to youtube, sorry bout that :(

**Comment by lephino** [comment]
Lol so that actually has to do with the max_out, which we did change in 6.  Long story short, there was an internal event queue that would build up events then drop them all at once.  In eg 6 that queue still exists, but now is only used when you have like "count=100000" and is flushed after every completed interval.  Have I thrown enough wrenches at you to catch yet?  And yeah, this was part of the major pieces of EG6, was to provide way more clarity and structure to how EG works.  Now the next step is to get all these nice neat structures defined and listed for you guys in the documentation. ;)

**Comment by JohnKruse** [comment]
Actually, I don't think that's it. My files are tiny - like 50 lines. Our
data sources are from device status reports generated every few min by
management tools (e.g., Solarwinds). Thus, I just want to do some
substitutions on certain fields and do a batch dump every 2 min using the
sample file over and over.

In the past, I think this worked because (according to the spec file) count
defaults to 0. Now, however, it is stopping after the sample is completed a
single time.

Any thoughts on why the Sample wouldn't start over? I was looking at the
Break parameter, but I'm not understanding what it does. I don't think
Bundlelines is what I want, as it isn't really a single "event".

Thanks, John
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by lephino** [comment]
post your .conf if you can (or the entire app). To me that should just be a count 0, interval 120.  Make sure you don't have a "end" key, as "end=1" means only repeat the sample one time.  Also make sure to check the .log files from eventgen, and make sure it didn't thrown an exception.  There's a bug in 6.2 where if the timestamp can't be parsed on 1 row, it bails.

**Comment by JohnKruse** [comment]
Hey Brian,
I tried to really boil down my eventgen.conf to the three Sample sources
that I'm having the most trouble with. They are now indexing and all seems
to be OK, but I had some odd problems. I wanted to tell you about my oddest
ones that I discovered just by doing some detective work with the conf and
sample files.

   - I had an old static date field that came right before the
   Replaytimestamp field in a SAMPLE type source. It was formatted as such
   "11/05/17 12:00". Despite the next field being the replaytimestamp, and I
   had not set up a token to recognize that format, it kept indexing based on
   those old 2017 date/times. It finally started working correctly when I
   changed the field to the form "11/05/17T12:00". I don't know why the
   inclusion of the "T" would cause it to not use the date for indexing, but
   it worked.
   - I started adding my sources to the eventgen.conf one by one to figure
   out what was going wrong. I have found that I can have a bunch of SAMPLE
   types in a conf file and it works well. I can have a bunch of REPLAY types
   together and they work fine. But if I put them together in the same conf
   file, the SAMPLES will run once upon starting and then will stop, and the
   REPLAYs will continue to chug along fine.
      - For this one, I'm going to try setting up a new app so that I have
      one for SAMPLEs and one for REPLAYs.
   - If I have a file with just SAMPLE type, I have to make count=0 to
   sample everything in the file. If I set a different number, it will just
   keep sampling the same events over and over. So, if I set count=5, I can go
   in after a few minutes and there will be multiple indexed events for the
   same 5 source events and the rest will be ignored.


THanks for all of your help, John
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by JohnKruse** [comment]
Here you go. The REPLAY entries for Eventgen.conf are in a file called
"eventgen.conf.hold". Each source has its own index, and they are
associated with an app that I can't share with you. They are listed below.

Have a great weekend and Thanks!
John


Name
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
ActionsType
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>App
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Current
Size
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Max
Size
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Event
Count
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Earliest
Event
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Latest
Event
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Home
Path
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>Frozen
Path
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Status
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
x_node_status_sw
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_node_status_sw?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_node_status_sw&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_node_status_sw?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_node_status_sw&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 402 MB 3.91 GB 12.1M 3 years ago an hour ago
$SPLUNK_DB/x_node_status_sw/db N/A
 Enabled
x_ipsla_udpj_sw
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_ipsla_udpj_sw?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_ipsla_udpj_sw&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_ipsla_udpj_sw?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_ipsla_udpj_sw&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 16 MB 1.95 GB 725K 12 days ago an hour ago
$SPLUNK_DB/x_ipsla_udpj_sw/db N/A
 Enabled
x_ipsla_tcpc_sw
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_ipsla_tcpc_sw?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_ipsla_tcpc_sw&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_ipsla_tcpc_sw?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_ipsla_tcpc_sw&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 16 MB 1.95 GB 730K 12 days ago an hour ago
$SPLUNK_DB/x_ipsla_tcpc_sw/db N/A
 Enabled
x_ex_svrs_scom
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_ex_svrs_scom?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_ex_svrs_scom&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_ex_svrs_scom?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_ex_svrs_scom&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 2 MB 2.44 GB 5.44K 10 months ago a minute ago
$SPLUNK_DB/x_ex_svrs_scom/db N/A
 Enabled
x_dc_util
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_dc_util?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_dc_util&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_dc_util?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_dc_util&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 5 MB 2.15 GB 29.9K 5 years ago a minute ago
$SPLUNK_DB/x_dc_util/db N/A
 Enabled
x_dc_scom
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_dc_scom?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_dc_scom&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_dc_scom?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_dc_scom&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 6 MB 1.95 GB 43.2K a year ago a minute ago
$SPLUNK_DB/x_dc_scom/db N/A
 Enabled
x_cto
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_cto?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_cto&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_cto?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_cto&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 4 MB 1.95 GB 28.3K 12 days ago a minute ago
$SPLUNK_DB/x_cto/db N/A
 Enabled
x_crewstatus
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_crewstatus?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_crewstatus&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_crewstatus?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_crewstatus&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 3 MB 1.95 GB 13.7K 12 days ago a minute ago
$SPLUNK_DB/x_crewstatus/db N/A
 Enabled
x_asi
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_asi?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_asi&ns=LeaderSA-App-624thAOC&action=edit>
Edit
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes/x_asi?uri=%2FservicesNS%2Fnobody%2FLeaderSA-App-624thAOC%2Fdata%2Findexes%2Fx_asi&ns=LeaderSA-App-624thAOC&action=edit>
 Delete
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
Disable
<http://localhost:8000/en-US/manager/LeaderSA-App-624thAOC/data/indexes#>
 Events LeaderSA-App-624thAOC 3 MB 1.46 GB 21.5K 12 days ago a minute ago
$SPLUNK_DB/x_asi/db N/A
 Enabled
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by JohnKruse** [comment]
Brian,
I just tried moving all of the REPLAY sources into a separate app. It still
shows the same behavior as the SAMPLE sources run once, but the REPLAYs
continue.
Hope you had a good holiday.
Thanks, JOhn
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by JohnKruse** [comment]
Brian,
I've been trying to move all of my sources over to being SAMPLEs just to
get things up and running. I'm getting this error consistently. I'm not
intentionally doing anything with Jinja (but maybe it is hidden behind the
scenes).
THanks, JK

9/5/18
9:04:38.000 AM
2018-09-05 09:04:38 eventgen ERROR MainProcess No module named jinja2
Traceback (most recent call last): File "/Applications/Splunk/etc/apps/SA-
Eventgen/lib/splunk_eventgen/eventgen_core.py", line 437, in _
initializePlugins module = imp.load_module(base, mod_name, mod_path, mod_
desc) File "/Applications/Splunk/etc/apps/SA-Eventgen/lib/splunk_eventgen/
lib/plugins/generator/jinja.py", line 9, in <module> from jinja2 import
nodes ImportError: No module named jinja2
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by lephino** [comment]
You can ignore that one, that's a traceback on an import, but it catches it safely.  "that's expected" when running inside of splunk.  If you want it to go away, download jinja2, and place it in your lib folder of sa-eventgen

**Comment by JohnKruse** [comment]
Thanks. If it isn't hurting anything, I'm happy forgetting it.

**Comment by JohnKruse** [comment]
Thanks Brian

**Comment by JohnKruse** [comment]
Hey Brian,
I went to your final session at .conf18. You had a good crowd for a final
session. I was going to say hi, but I had to get going to meet a colleague.
By way of feedback, it was a great conference and everything ran far
smoother than I would ahve imagined given the number of attendees.

I was wondering if you've had a chance to do check out any of this. If not,
I think I might roll back to an older version of Eventgen. I don't know if
there is a stable copy of 6.1 out there. Any ideas?

Thanks, John
============================================
John Kruse   john@kruser.org   781.333.8349

* "A complex system that works is invariably found to have evolved from a
simple system that worked. A complex system designed from scratch never
works and cannot be patched up to make it work. You have to start over with
a working simple system." – John Gall*

**Comment by lephino** [comment]
I’m actually looking at it today / tomorrow! lol funny you should ask!  I’m trying to get prepped to ship out 6.3, and I want to make sure there’s nothing in this issue that would hold it up

**Comment by JohnKruse** [comment]
Sometimes my psychic powers are astounding!
Thanks

**Comment by arctan5x** [comment]
6.3. has been shipped. Would appreciate if you can reconfirm the issue on that version.

**Comment by lephino** [comment]
@JohnKruse were you still having an issue?  Or we good to close this one out?

**Comment by lephino** [comment]
Closing this issue since we haven't heard back in a few months.  Feel free to reopen if I didn't get your issue fixed!
